### ISSUE TITLE
[BUG] Test of local channel backup fails

### ISSUE THREAD

**Issue by nicheosala** [raspibolt/raspibolt#1029]
### Describe the bug
The local channel backup fails.

### Location in guide
[Link to the corresponding page and section on <https://raspibolt.org>](https://raspibolt.org/guide/lightning/channel-backup.html#test-1)

### Expected behavior
In the logs of scb-backup, according to the guide, I should see:
```
Success! The file is now remotely backed up!
```

### Screenshots
Instead, these are the logs:
```
May 24 18:27:18 raspberrypi systemd[1]: Started SCB Backup daemon.
May 24 18:27:18 raspberrypi scb-backup[1542]: Setting up watches.
May 24 18:27:18 raspberrypi scb-backup[1542]: Watches established.
May 24 18:36:46 raspberrypi scb-backup[1542]: /data/lnd/data/chain/bitcoin/mainnet/channel.backup OPEN
May 24 18:36:46 raspberrypi scb-backup[1541]: channel.backup has been changed!
May 24 18:36:46 raspberrypi scb-backup[1541]: Local backup is enabled
May 24 18:36:46 raspberrypi scb-backup[1541]: Copying backup file to local storage device...
May 24 18:36:46 raspberrypi scb-backup[1541]: /mnt/static-channel-backup-external/channel-20220524-183646.backup
May 24 18:36:46 raspberrypi scb-backup[1604]: cp: cannot create regular file '/mnt/static-channel-backup-external/channel-20220524-183646.backup': Permission denied
May 24 18:36:46 raspberrypi systemd[1]: scb-backup.service: Main process exited, code=exited, status=1/FAILURE
May 24 18:36:46 raspberrypi systemd[1]: scb-backup.service: Failed with result 'exit-code'.
```

### Environment
 - Hardware platform: Raspberry Pi 4
 - Operating system: Raspberry Pi OS 64bit
 - Version: Debian GNU/Linux 11 (bullseye)

**Comment by icuntcode** [comment]
It looks like you don´t have permissions on the local folder (/mnt/...).

Make sure you set the right GID and UID for the user lnd as described here: https://raspibolt.org/guide/lightning/channel-backup.html#option-1-local-backup
