### ISSUE TITLE
[BUG] `poetry install` in CLN bonus guide fails for me

### ISSUE THREAD

**Issue by kristapsk** [raspibolt/raspibolt#1057]
### Describe the bug
```
$ poetry install
Creating virtualenv cln-meta-project-TpDLTRw9-py3.8 in /home/cln/.cache/pypoetry/virtualenvs

  ModuleNotFoundError

  No module named 'virtualenv.seed.via_app_data'

  at <frozen importlib._bootstrap>:973 in _find_and_load_unlocked
```

### Location in guide
https://raspibolt.org/guide/bonus/lightning/cln.html

### Expected behavior
Command should not fail.

### Environment
 - Hardware platform: Odroid HC4
 - Operating system: Ubuntu Server
 - Version: Ubuntu 20.04.4 LTS

### Additional context
Any dependencies I may be missing? `virtualenv` itself is installed.

Also noticed in [most recent CLN install guide](https://github.com/ElementsProject/lightning/blob/af2b863b4a3a5e56c10ba20a1af5ff969379543c/doc/INSTALL.md), it now has `poetry run make` instead of `make`.

**Comment by blckbx** [comment]
Thanks for the hints! I will add the new installation commands to #1056

Regarding virtualenv: https://stackoverflow.com/questions/63491221/modulenotfounderror-no-module-named-virtualenv-seed-embed-via-app-data-when-i Could this be some kind of version clash of virtualenv?

**Comment by blckbx** [comment]
Updated my amd64 installation with these new poetry instructions just fine. Not sure if it's some configuration issue

**Comment by kristapsk** [comment]
I also don't have issues with `poetry install` on amd64 Gentoo, but I do have on that specific arm64 Ubuntu. Will try to figure out what's wrong there.

**Comment by ericsupreme** [comment]
same here. attached is the error message i get one running poetry install
![poet](https://user-images.githubusercontent.com/38678012/188681281-d801cfbf-eabb-40dc-87d3-5bf09bdff251.jpg)

**Comment by ericsupreme** [comment]
> I also don't have issues with `poetry install` on amd64 Gentoo, but I do have on that specific arm64 Ubuntu. Will try to figure out what's wrong there.

were you able to figure anything out??

**Comment by kristapsk** [comment]
> were you able to figure anything out??

No, not yet.

**Comment by kristapsk** [comment]
@ericsupreme But your error looks different, could be something else.

**Comment by ericsupreme** [comment]
> @ericsupreme But your error looks different, could be something else.

yes definitely but i caould at least start somewhere, i'm stumped lol
