### ISSUE TITLE
[FEATURE REQ] LND remote static channel backups should be pushed via Tor

### ISSUE THREAD

**Issue by kristapsk** [raspibolt/raspibolt#1065]
### What & why

Currently RaspiBolt configures LND to work as .onion service only by default. But remote static channel pushes to github.com happen using clearnet. This way your real IP address ir revealed to github.com (Microsoft), together with your channel information.

### How

git pushes should happen using SOCKS5 localhost Tor proxy.

### Location in guide

https://raspibolt.org/guide/lightning/channel-backup.html#option-2-remote-backup-preparations

**Comment by twofaktor** [comment]
How do you suggest this could be deployed? Which commands to change?

**Comment by kristapsk** [comment]
Not sure yet. Either git can be configured to do this somehow or maybe `torsocks` could be used.

**Comment by blckbx** [comment]
probably via
`git config --global http.proxy http://127.0.0.1:9050`
and I guess we have to be torified (TorBrowser) right from the start at the time of the github account and repo creation as well.

**Comment by kristapsk** [comment]
> `git config --global http.proxy http://127.0.0.1:9050`

Don't think that will work, Tor provides SOCKS5 proxy, not a HTTP proxy.

**Comment by blckbx** [comment]
https://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport
despite the naming, socks5 should also work here (to be tested)
`git config --global http.proxy 'socks5://127.0.0.1:9050'`

**Comment by kristapsk** [comment]
Ok, likely next problem, static channel backups is pushed to github via ssh not http. But [`core.sshCommand`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand) setting seems to be the right one:

> **core.sshCommand**
> If this variable is set, `git fetch` and `git push` will use the specified command instead of `ssh` when they need to connect to a remote system. The command is in the same form as the `GIT_SSH_COMMAND` environment variable and is overridden when the environment variable is set.
