### ISSUE TITLE
I2P running for a few weeks, no connected peers yet..?

### ISSUE THREAD

**Issue by VajraOfIndra** [raspibolt/raspibolt#1080]
### Describe the issue
I followed this guide to run I2P: https://raspibolt.org/guide/bonus/bitcoin/i2p.html

After a few weeks, still no peers. I suspect there is an issue somewhere...
![image](https://user-images.githubusercontent.com/86242283/187674527-00c2159b-f64e-4a0f-868d-f8a552336b4c.png)

### Location in guide
[Link to the corresponding page and section on <https://raspibolt.org>](https://raspibolt.org/guide/bonus/bitcoin/i2p.html)

### Screenshots
I2P service is active:
![image](https://user-images.githubusercontent.com/86242283/187674669-1770eb41-e207-4b2c-92fe-91c486b50da6.png)

### Environment
 - Hardware platform: Raspberry Pi 4 4GB
 - Operating system: RasPiOS Lite 64bit
 - Version: Debian GNU/Linux 11 (bullseye)

### Additional context
Logs output:

> admin@raspibolt:~ $ sudo tail -f /var/log/i2pd/i2pd.log
> 13:00:19@245/warn - SSU2: Session with 37.204.86.74:9718 was not established after 5 seconds
> 13:00:43@329/error - Garlic: Failed to decrypt message
> 13:00:46@726/warn - NTCP2: SessionCreated read error: End of file
> 13:00:47@352/warn - NetDb: Destination xjboEpb8uwkMPcy2uzu8I63W-oznn91M0nD~6ofswXQ= is requested already
> 13:01:29@329/error - Garlic: Failed to decrypt message
> 13:02:32@726/warn - NTCP2: SessionCreated read error: End of file
> 13:03:06@846/warn - Tunnels: Test of tunnel 2341950696 failed
> 13:03:11@846/warn - Tunnels: Test of tunnel 2819269901 failed
> 13:03:57@751/warn - Transports: Session to peer ZEnMpbQzgZwAOGdtvS5oKltYYKzfN35~G8kWbT0KeRo= has not been created in 15 seconds
> 13:04:06@846/warn - Tunnels: Test of tunnel 1738627153 failed
> 13:04:36@846/warn - Tunnels: Test of tunnel 508700813 failed
> 13:04:46@846/warn - Tunnels: Test of tunnel 224718362 failed
> 13:04:47@726/warn - NTCP2: SessionCreated read error: End of file
> 13:05:06@726/warn - NTCP2: Receive length read error: End of file
> 13:05:13@329/error - Garlic: Failed to decrypt message
> 13:05:16@846/warn - Tunnels: Test of tunnel 3144601582 failed
> 13:05:18@726/warn - NTCP2: SessionCreated read error: End of file
> 13:05:18@352/warn - NetDb: Destination henVNN0cDWwNMcvrDZnnnHDf5e~I~57iVpQpiHEhOFg= is requested already
> 13:05:29@329/error - Garlic: Failed to decrypt message
> 13:05:41@846/warn - Tunnels: Test of tunnel 369296486 failed
> 13:06:12@726/warn - NTCP2: SessionCreated read error: End of file
> 13:06:26@846/warn - Profiling: No profile yet for 1dMtr5HyvIIUXtxSebw1tV1-CyMrvAg-ipSGTN-Ft7E=
> 13:07:19@726/warn - NTCP2: Receive length read error: End of file
> 13:07:28@329/error - Garlic: Failed to decrypt message
> 13:07:31@846/warn - Tunnels: Test of tunnel 1593075819 failed

**Comment by kristapsk** [comment]
I would suggest to try manually connect to some I2P peers listed here - https://github.com/bitcoin/bitcoin/blob/master/contrib/seeds/nodes_main.txt (`bitcoin-cli addnode <address> add`). Also, does `bitcoin-cli -netinfo` shows your I2P address?

**Comment by VajraOfIndra** [comment]
> I would suggest to try manually connect to some I2P peers listed here - https://github.com/bitcoin/bitcoin/blob/master/contrib/seeds/nodes_main.txt (`bitcoin-cli addnode <address> add`). 

Thanks! Done. I'll monitor the peer count now that I have one..

> Also, does `bitcoin-cli -netinfo` shows your I2P address?

Yes, with port 0 and score 4

**Comment by twofaktor** [comment]
Yeah i2p is running with port 0 by the way: I have 3 incoming peers, i2p is growing little by little 🚀 all cleared? 

<img width="364" alt="Captura" src="https://user-images.githubusercontent.com/89636253/188608849-bf655144-f9fe-4da9-bceb-7e1c93ee1e36.PNG">

Can this support ticket be closed?

**Comment by soc7** [comment]
usually restarting the service fixes it.
