### ISSUE TITLE
Syntax Typos in: Lightning Client Opening a Channel

### ISSUE THREAD

**Issue by dunwright** [raspibolt/raspibolt#1092]
### Describe the bug
Syntax typos in "Open a channel" section:
The command **as** a built-in fee estimator...
...by using the **`sat_per_byte`** argument as follows...

### Location in guide
https://raspibolt.org/guide/lightning/lightning-client.html#opening-channels

### Expected behavior
The command **has** a built-in fee estimator...
...by using the **`sat_per_vbyte`** argument as follows...

### Screenshots
![image](https://user-images.githubusercontent.com/704363/190693782-91bf052d-6aca-417b-8e8c-1e319fd2a969.png)

### Environment
N/A

**Comment by VajraOfIndra** [comment]
Well spotted, thanks! (and very clean illustration :100:)

Created #1093 to fix this.
