### ISSUE TITLE
[FEATURE REQ] Add guide for Jam (web UI for JoinMarket)

### ISSUE THREAD

**Issue by kristapsk** [raspibolt/raspibolt#1098]
### What & why

[Jam](https://github.com/joinmarket-webui/jam) is a user friendly web UI for JoinMarket. It's already available for RaspiBlitz, Umbrel and Citadel. Would be cool to have Jam guide for RaspiBolt as well.

### How

First JoinMarket guide for RaspiBolt v3 should be merged (#1085). Then either instructions for Jam should be added to that guide or separate guide should be written.

**Comment by VajraOfIndra** [comment]
#1085 has now been merged.
Do you recommend a separate guide for Jam or a new section within the JoinMarket guide?

**Comment by kristapsk** [comment]
Don't have a strong opinion on this currently.
