### ISSUE TITLE
Balance of Satoshis - Circular Rebalancing Typo? 

### ISSUE THREAD

**Issue by dunwright** [raspibolt/raspibolt#1099]
### Describe the bug
multiple instances of bos command syntax ends with:
--out [NODE_**A**_PUBKEY]

### Location in guide
https://raspibolt.org/guide/bonus/lightning/balance-of-satoshis.html#circular-rebalancing

### Expected behavior
Shouldn't that syntax end with?:
--out [NODE_**B**_PUBKEY]

### Screenshots
![image](https://user-images.githubusercontent.com/704363/191177653-7188f48d-5f2a-43b1-ad80-87ead8536801.png)

### Environment
N/A

### Additional context
Example command syntax provided using Bitrefill node as node 'B' ends with --out using Bitrefill's pubkey.

**Comment by VajraOfIndra** [comment]
Well spotted, thanks a lot! Can't believe I spent all that time explaining how the rebalancing works and still screwing up the actual command 😅 

I made a fix with #1100 .. should be merged soon! (this issue will close automatically, once that pull request will be merged)

**Comment by VajraOfIndra** [comment]
> No sweat... documentation is complicated (especially keeping it up to date with changes in subcomponent versions). 

Yes, I get that, I feel we're always behind haha

> This project has me excited about technology again...

Nice to hear this ❤️ 
Me it got me learning about Linux and FOSS, just for that I'm thankful! :)

> I work for a large global cybersecurity manufacturer

Sounds pretty cool! I hope you don't mind me asking but if you can see ways we could harden the security of the whole setup, we'd love to hear about them!

Thanks for your help on this issue anyways, much appreciated.
