### ISSUE TITLE
error message i get when running poetry install

### ISSUE THREAD

**Issue by ericsupreme** [raspibolt/raspibolt#1106]
same here. attached is the error message i get when running poetry install
![poet](https://user-images.githubusercontent.com/38678012/188681281-d801cfbf-eabb-40dc-87d3-5bf09bdff251.jpg)
i'm running a rasp pi 400 ( i know!! lol)

_Originally posted by @ericsupreme in https://github.com/raspibolt/raspibolt/issues/1057#issuecomment-1238344061_

**Comment by kristapsk** [comment]
There is no `poetry install` in updated CLN instructions anymore. https://raspibolt.org/guide/bonus/lightning/cln.html

**Comment by ericsupreme** [comment]
ahhhh

> There is no `poetry install` in updated CLN instructions anymore. https://raspibolt.org/guide/bonus/lightning/cln.html

ahhhh ty very much for the speedy reply. i will give it a whirl!!
