### ISSUE TITLE
[FEATURE REQ] Set tlsautorefresh=true in default lnd.conf (pros/cons?)

### ISSUE THREAD

**Issue by VajraOfIndra** [raspibolt/raspibolt#1115]
### What & why

According to the [official documentation](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf):
> ; If set, then all certs will automatically be refreshed if they're close to 
> ; expiring, or if any parameters related to extra IPs or domains in the cert 
> ; change.
> ; tlsautorefresh=true

Setting it to true would prevent potential issues and downtimes for users once their certificate expires.

Raspiblitz has this option as true in their [default config file](https://github.com/rootzoll/raspiblitz/blob/v1.8/home.admin/config.scripts/lnd.install.sh).

Any reasons why we should NOT do this?

If we decide to include this option in the default config for the guide, we probably need to also look into related TLS certif options, e.g. `tlsdisableautofill`.

### How

Edit default `lnd.conf` in [this section of the guide](https://raspibolt.org/guide/lightning/lightning-client.html#configuration).

### More context

Check the short discussion in the Telegram group with @vicariousdrama starting at [this post](https://t.me/raspibolt/13653).

**Comment by vicariousdrama** [comment]
ACK.

I'm in favor of setting tlsdisableautofill to `true`.  See descriptions of these fields here in the LND source: https://github.com/lightningnetwork/lnd/blob/master/config.go#L269

In this case, setting the value for tlsdisableautofill to true is a stronger security posture then setting it to false.  When true the cert would then be issued to only be valid on the local host (127.0.0.1 and ::1), as well as anything included in extra IPs (set with tlsextraips).
