### ISSUE TITLE
LNDG is not shown in browser with 502 bad Gateway. 

### ISSUE THREAD

**Issue by ohohora** [raspibolt/raspibolt#1125]
I followed latest updated Lndg guide_10/13 (there is a link below). Before installing uwsgi, it worked on http://raspibolt.local:8889 but After setting up uwsgi, nginx, etc (web server configuration part), it no longer works on https://raspibolt.local:8889. It says 502 bad gateway. 
I restarted uwsgi, nginx but didn't work. And nginx error log file (/var/log/nginx/error.log) is as following :

2022/10/14 03:37:16 [crit] 990#990: *202 connect() to unix:///home/lndg/lndg/lndg.sock failed (13: Permission denied) while connecting to upstream, client: xx.xx.xx.xx, server: _, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/lndg/lndg/lndg.sock:", host: "raspibolt.local:8889"

lndg.sock file has been applied 660 well by the chmod, chown commands. 
srw-rw---- 1 lndg www-data     0 Oct 18 02:14 lndg.sock
I also restarted nginx, uwsgi but still don't work. 
I dont' know what's going on. Will appreciate with your help. 

### Location in guide
https://github.com/VajraOfIndra/RaspiBolt/blob/LNDg/guide/bonus/lightning/lndg.md

### Environment
 - Hardware platform: PC (amd64)
 - Operating system: ubuntu 22.04

**Comment by Buttafuoco** [comment]
I have same issue with 400 code. The only way to connect is via HiddenService

**Comment by ohohora** [comment]
Now It works on https://raspibolt.local:8889 by two ways each below. 

1. Adding user 'www-data' to group 'lndg' 
          $ sudo adduser --disabled-password --gecos "" lndg
          $ sudo adduser lndg lnd
          $ sudo adduser lndg www-data
          **$ sudo adduser www-data lndg**

or

2. Changing the user from 'www-data' to 'lndg' in /etc/nginx/nginx.conf 
          $ sudo nano /etc/nginx/nginx.conf 
            **#user www-data;
            user lndg;**
            worker_processes 1;

Maybe got rid of permission error(502 bad gateway) but these methods looks a bit weired. I doubt that if it will mess up nginx related services or other things. Need some advice, comments~!

**Comment by VajraOfIndra** [comment]
> Now It works on https://raspibolt.local:8889 by two ways each below.
> 
>     1. Adding user 'www-data' to group 'lndg'
> [...]
> 
> or
>     2. Changing the user from 'www-data' to 'lndg' in /etc/nginx/nginx.conf
> [...]

Option 2 is not possible as this is the default nginx config file which is used for other apps (e.g. Mempool, Homer...)

Option 1 should be feasible I think.. The weird thing is that I have LNDg running on mine without having to have done that.. I'm not sure what's different on my setup vs the draft guide. 

I'm very new to nginx, uwsgi and Python stuff and it's so layered..! it's hard to keep track of how all the pieces work together..

**Comment by ohohora** [comment]
Thanks~!!!  I'll run LNDg on option1.

**Comment by VajraOfIndra** [comment]
> Like you said, option 1 looks feasible and thank you~!!!

Sounds good if it works for you for now but it shouldn't be necessary. I can access LNDg via https without this additional step for example (but don't know why yet! :). I'm reworking the guide to try to solve these permissions issues and find the best prtactices, keep an eye on the main PR.

**Comment by ohohora** [comment]
I also it looks unnecessary step. I'll keep an eye on main PR~!!!

**Comment by blckbx** [comment]
This is indeed a strange edge case. Looks like we got at least 
- 2 successful installations on Raspberry PIs that worked without adding www-data to lndg group and 
- 2 installations (ohohora and myself) on Ubuntu 22.04 that only worked by adding www-data to lndg group

I'm just guessing but it could be OS related.

**Comment by VajraOfIndra** [comment]
I'll make www-data a member of the lndg group in the guide, like that it works for any platform.

I was thinking of the security consideration of giving www-data some lndg group permissions.. but I don't think it creates any real secuirty concerns.

**Comment by ohohora** [comment]
OK. maybe related to OS like blckbx said....? Anyway, I hope official guide of LNDg will come out well~!!!

**Comment by ohohora** [comment]
OK. Maybe related to OS like blckbx said...? Anyway, I wish official LNDg guide will come out well~!!!
