### ISSUE TITLE
[BUG] apt-key is deprecated warning

### ISSUE THREAD

**Issue by sig-noi** [raspibolt/raspibolt#1174]
### Describe the bug
Importing repo signing keys with apt-key results in the following warning:
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

### Location in guide
Definitely occurs in the i2p bonus guide. Does not seem to be an issue for tor install. Unsure if there are other locations where it occurs.

### Expected behavior
Change instructions to manage keyring files in trusted.gpg.d rather than apt-key

### Screenshots
n/a

### Environment
 - Hardware platform: [Raspberry Pi 4]
 - Operating system: [Raspberry Pi OS 64bit]
 - Version: [Debian GNU/Linux 11 (bullseye)]

**Comment by kristapsk** [comment]
Only place where there is `apt-key` mentioned in RaspiBolt guides is [Odroid XU bonus guide](https://github.com/raspibolt/raspibolt/blob/master/guide/bonus/raspberry-pi/odroid-setup.md). For I2P guide currently https://repo.i2pd.xyz/.help/add_repo is downloaded and trusted, so either guide should be changed to not do that or issue should be solved in upstream (i2pd).

But I can't reproduce mentioned warning on my system (Ubuntu Server 20.04).
```
admin ~ ₿ wget -q -O - https://repo.i2pd.xyz/r4sas.gpg | sudo apt-key --keyring /etc/apt/trusted.gpg.d/i2pd.gpg add -
OK
```
