### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kyu-coder** [raspibolt/raspibolt#1186]
### Describe the bug

admin@raspibolt:~ $ sudo ufw allow ssh

WARN: initcaps

[Errno 2] iptables v1.8.7 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)

Perhaps iptables or your kernel needs to be upgraded.

### Location in guide
Link to the corresponding page and section on <https://raspibolt.org>

https://raspibolt.org/guide/raspberry-pi/security.html#enabling-the-uncomplicated-firewall

### Expected behavior

no error after  "sudo ufw allow ssh"

### Environment
 - Hardware platform: [e.g. Raspberry Pi 4, Odroid, ... ]
 Raspberry Pi 4
 - Operating system: [e.g, Raspberry Pi OS 64bit, Debian 11, ... ]
 - Version: [ output of `lsb_release -d` ]

### Additional context

https://www.reddit.com/r/raspibolt/comments/yz6qsq/comment/ix4ke9x/?context=3

**Comment by twofaktor** [comment]
No problems following the RaspiBolt guide:

![Captura2331424](https://user-images.githubusercontent.com/89636253/203560035-bad7ce14-1e3b-41cd-8a7c-c3b0dab4b00a.PNG)
