### ISSUE TITLE
[FEATURE REQ]  ots validation for bitcoin core upgrades

### ISSUE THREAD

**Issue by sig-noi** [raspibolt/raspibolt#1190]
### What & why

Would be nice to add .ots verification step for upgrading bitcoin core. Added security for upgrading users.

### How

Would replicate pared down Installation section including additional .ots file download and verification steps to the Upgrade section of the Bitcoin guide. This would make the whole installation process more straightforward as upgrading users also shouldn't need to worry about downloading gpg keys as described in initial Install section. Could also add a command to refresh gpg keys as bitcoincore.org recommends. `gpg --keyserver hkps://keys.openpgp.org --refresh-keys`

### Additional context
n/a

**Comment by twofaktor** [comment]
Own comment about this here: https://github.com/raspibolt/raspibolt/pull/1191#discussion_r1032180497
