### ISSUE TITLE
Need more information on lightning/lightning-client guide

### ISSUE THREAD

**Issue by smartm0use** [raspibolt/raspibolt#1236]
I'm installing lnd following this [guide](https://raspibolt.org/guide/lightning/lightning-client.html) and I would to figure out better what I doing.

![image](https://user-images.githubusercontent.com/5399265/215360655-eb698aee-706d-478a-9b37-c93f95856d59.png)

About this part... I know that **debian-tor** group is generated when I install tor, instead... who is **bitcoin** group?
I haven't that group on my machine (and it has not been created when I installed Bitcoin Core).

Is this could be an issue for running lnd and connecting it to Bitcoin Core daemon?

I'm on Ubuntu 20.04.

**Comment by twofaktor** [comment]
If you haven't Bitcoin group is because didn't follow the guide:
https://raspibolt.org/guide/bitcoin/bitcoin-client.html#create-the-bitcoin-user

BTW: RaspiBolt was built on Raspbian Lite OS, not Ubuntu, please follow the RaspiBolt guide since first
