### ISSUE TITLE
New release of c-lightning-REST v0.10.0

### ISSUE THREAD

**Issue by kristapsk** [raspibolt/raspibolt#1241]
There is new release of c-lightning-REST v0.10.0 - https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.0.

Core Lightning bonus guide likely needs to be updated. By somebody who uses CLN with RaspiBolt.

**Comment by kristapsk** [comment]
Ping @blckbx

**Comment by kristapsk** [comment]
There's some breaking changes in Core Lightning v22.11.0+, c-lightning-REST needs to be updated to v0.10.1. https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.1

**Comment by blckbx** [comment]
PR updated, hotfix relates to offer api.

**Comment by kristapsk** [comment]
> PR updated, hotfix relates to offer api.

Noticed Core Lightning bonus guide has v0.11.2 currently. Guess that also should be updated to newer version.

**Comment by blckbx** [comment]
> Noticed Core Lightning bonus guide has v0.11.2 currently. Guess that also should be updated to newer version.

Yes, that's mentioned in CLN-rest PR. PR is still waiting for approval (#1210)

**Comment by kristapsk** [comment]
> > Noticed Core Lightning bonus guide has v0.11.2 currently. Guess that also should be updated to newer version.
> 
> Yes, that's mentioned in CLN-rest PR. PR is still waiting for approval (#1210)

Sorry, missed that!

**Comment by blckbx** [comment]
Nobody's fault. I was hoping for some testers.
