### ISSUE TITLE
RTL - Boltz/Loop Macaroons Missing

### ISSUE THREAD

**Issue by webforma** [raspibolt/raspibolt#1242]
### Describe the issue
I followed the guide and got the node up and running for starters.  So, thank you for the great guide. 
 Now that I'm tinkering with it, I am unable to get Loop and Boltz connected within the RTL web app. 
 I get 503 API errors in the web app after clicking on either link under the Services menu in the RTL web app. 

I did not find steps to update the macaroon path in the guide.  In the RTL_Config.json, there are paths that need to be set.  I did try setting the Boltz macaroon path to /home/rtl seeing if it can use the admin.macaroon in that location.  That does not seem to work or there is still some other configuration that needs to be done.  

Journalctl (rtl) shows there is a connection error when Boltz starts up in the RTL web app: 
`ERROR: Boltz => List Swaps Error: {"name":"RequestError","message":"Error: connect ECONNREFUSED 127.0.0.1:9003","cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9003},"error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9003},"options":{"url":"https://127.0.0.1:9003/v1/listswaps","rejectUnauthorized":false,"json":true,"headers":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}`

Anybody have any suggestions on this one?  

### Location in guide
 (https://raspibolt.org/guide/lightning/web-app.html)

### Screenshots
![image](https://user-images.githubusercontent.com/123883009/217869690-ef70b217-1716-42e7-bdc1-9ce63349b16a.png)

### Environment
 - Hardware platform: Rock64
 - Operating system: Debian 
 - Version: 	Debian GNU/Linux 9.13 (stretch)

**Comment by blckbx** [comment]
Omit/delete these two lines, if you don't intend to run Boltz or Loop services. These are not described in the guide afaik.
```ini
  "swapServerUrl": "https://127.0.0.1:8081"
  "boltzServerUrl": "https://127.0.0.1:9003"
```
