### ISSUE TITLE
Error starting bitcoind

### ISSUE THREAD

**Issue by giovannidibenedettogdb** [raspibolt/raspibolt#1253]
Hi, I'm trying to run my node on a linux machine Ubuntu 20.10. I followed the step by step guide, cnfigurato the SSH server, the reverse proxy and TOR. Now I'm stuck at the installation of BitcoinCore. After verifying the signatures of the files, creating the bitcoin user and modifying the various config files I only miss the startup of bitcoinb. The problem is that when I launch the command the system gives me this error:

-bash: /usr/local/bin/bitcoind: Unable to run binary: Invalid executable format

could you tell me how to solve? Thank you very much

**Comment by twofaktor** [comment]
You are in the wrong guide:

Follow MiniBolt to amd64 architecture

https://minibolt.info

Follow RaspiBolt step-by-step to arm64 architecture (Raspberry Pi 4)
