### ISSUE TITLE
[BUG] wrong instruction to start Homer in "Bonus guide: Homer"

### ISSUE THREAD

**Issue by dutu** [raspibolt/raspibolt#1259]
### Describe the bug

In [Bonus guide: Homer](https://raspibolt.org/guide/bonus/raspberry-pi/homer.html),  Section "[First start](https://raspibolt.org/guide/bonus/raspberry-pi/homer.html#first-start)" the command: `npm run serve` doesn't work anymore.

### Expected behavior

Sections "First Start" and "Autostart on boot" needs to be removed, as there is no "running homer". 

Instead `npm run build` has to be executed, to generate the static html files. This has to be just done before moving the distributable output into the nginx website data folder, in section [Website data folder](https://raspibolt.org/guide/bonus/raspberry-pi/homer.html#website-data-folder).

### Additional context
* The same issue has been reported in #1222
* According to the response on issue ["Homer on Raspibolt"](https://github.com/bastienwirtz/homer/issues/510), there is no `npm run serve` command, the build command generates simple html static files which have to be hosted somewhere (behind a webserver)

**Comment by dutu** [comment]
Can any of the maintainers check this one? There is no point keeping a bonus guide that cannot be used.

**Comment by kristapsk** [comment]
I don't use Homer myself, can't check.
