### ISSUE TITLE
[FEATURE REQ] Tailscale

### ISSUE THREAD

**Issue by Satsuma-LN** [raspibolt/raspibolt#1265]
Tailscale is: "A remote-access VPN that works with your Identity Provider"

I managed to install Tailscale on my RaspiBolt following the guide by Tailscale (https://tailscale.com/download/linux).

I am not sure if this is the optimal/most secure way of setting up Tailscale but it works well for accessing my node via ssh remotely and for accessing my mempool explorer and ThunderHub when I'm not at home. But I could not get Zeus wallet to connect using the Tailscale ip address.

It is my understanding that using a vpn such as Tailscale instead of Tor is faster and more useable so I believe this is a useful feature to add.

**Comment by Mynima** [comment]
Can you take a look at https://github.com/raspibolt/raspibolt/pull/1227 see if you have any comments/feedback on this PR?
