### ISSUE TITLE
LevelDB fatal error

### ISSUE THREAD

**Issue by iTzNikolovich** [raspibolt/raspibolt#1272]
### Describe the issue
Hi all, after months of synchronization today, following a power outage, bitcoin-cli seems to never start. I hope someone can help me. Below are the logs, thanks in advance.

### Screenshots
<img width="1060" alt="Screenshot 2023-05-01 at 16 10 31" src="https://user-images.githubusercontent.com/64737169/235464661-716075f0-c3ce-4ebb-9069-0d8629a6f9c6.png">

### Environment
 - Hardware platform: [Fujitsu Futro S720]
 - Operating system: [Debian 11]
 - Version: [Debian GNU/Linux 11 (bullseye)]

Here is my [debug.log](https://github.com/raspibolt/raspibolt/files/11365837/debug.log)

**Comment by twofaktor** [comment]
Did you follow the RaspiBolt guide? (RaspiBolt is for Raspberry Pi)

**Comment by iTzNikolovich** [comment]
> Did you follow the RaspiBolt guide? (RaspiBolt is for Raspberry Pi)

Following raspibolt you can install all you need also on a x86 server... This is linux

**Comment by iTzNikolovich** [comment]
Solved with `bitcoind -reindex`. You must have to stop the node and then you can run this command from bitcoin user

**Comment by twofaktor** [comment]
> > Did you follow the RaspiBolt guide? (RaspiBolt is for Raspberry Pi)
> 
> Following raspibolt you can install all you need also on a x86 server... This is linux

minibolt.info
