### ISSUE TITLE
[FEATURE REQ] Raspibolt+ArchLinux

### ISSUE THREAD

**Issue by barbastrejo12** [raspibolt/raspibolt#1281]
I tried installing raspibolt adapting the guide to an arch install, but as I am not very technical I found some problems with the first config files as the differ a lot. But I think it would be of great beneficial for those who like arch, because as debian it's backed by a huge comunity of very talented people that very often did not understand bitcoin yet.
So if anyone has the knowledge and the will to do so, I am glad to test and try.

**Comment by kristapsk** [comment]
Almost every guide uses `apt`, which is Debian specific package manager, also Debian style configs, as you mentioned. For distributions not based on Debian, you would need to rewrite most of the stuff. It makes more sense to fork this guide, modify for Arch and then keep it up to date separately.
