### ISSUE TITLE
Unable to connect to Lightning Terminal by visiting web UI

### ISSUE THREAD

**Issue by harkousb** [raspibolt/raspibolt#1295]
Trying to complete the step to test the connection via web UI in 'Run Lightning Terminal' section of [https://raspibolt.org/guide/bonus/lightning/lightning-terminal.html#upgrade]

> "Test that Lightning Terminal is working by visiting the web UI
> 
> Paste the following URL in your browser: [https://raspibolt.local:8444/](https://raspibolt.local::8444/) (replace raspibolt.local by your node IP address if required)"

I accepted the SSL certificate, and I see the following:

![Screenshot from 2023-06-12 00-19-32](https://github.com/raspibolt/raspibolt/assets/39776417/7f671b2a-8b80-4ff1-af83-a455dedc273d)

I'm able to login to Lightning Terminal from my node directly via https://localhost:8444/, but not from my other PC.

**Comment by harkousb** [comment]
Getting connection refused on port 8443 when trying to use loop via CLI.

![Screenshot from 2023-06-24 11-28-01](https://github.com/raspibolt/raspibolt/assets/39776417/7c8e5115-82e1-4a00-8034-be9d2a8b4711)

Any ideas why this could be?

**Comment by harkousb** [comment]
If I manually run litd as user lit, I'm able to run CLI commands.

litd.service is running, status is active, but litd.service isn't automatically running litd?

**Comment by derekross** [comment]
I have a brand new install and I'm getting the same error from https:my-host.local:8443

Client sent an HTTP request to an HTTPS server.

 LND Version             0.16.4-beta commit=v0.16.4-beta                               
 LiT Version             0.10.2-alpha commit=v0.10.2-alpha

**Comment by atamti** [comment]
I worked through the issue in the NGINX reverse proxy and found this to be the issue: 
Lightning Terminal only deals in https:

https://github.com/lightninglabs/lightning-terminal/blob/master/doc/letsencrypt.md

But the SSL after "listen 8444" in the nginx config in the guide terminates the SSL connection and sends the requests as http.

Location in guide: https://raspibolt.org/guide/bonus/lightning/lightning-terminal.html#firewall--nginx

Removing the SSL resolved the issue for me, as it allows the traffic to simply be passed through encrypted to the lightning terminal app, which will then handle the decryption:

stream {
    upstream litd {
        server 127.0.0.1:8443;
    }

    server {
        listen 8444;
        proxy_pass litd;
    }
}

Recommend devs look into this to see if it's a universal issue and modify the guide accordingly.

**Comment by harkousb** [comment]
Worked for me! Thanks!

**Comment by dawiepoolman** [comment]
Yes, worked for me too thx.
sudo nano /etc/nginx/streams-enabled/litd-reverse-proxy.conf

```
upstream litd {
    server 127.0.0.1:8443;
}

server {
    listen 8444;
    proxy_pass litd;
}
```

**Comment by orangeshyguy21** [comment]
Great find! Also confirming that this fixes the issue.
