### ISSUE TITLE
Upgrading to Debian Bookworm

### ISSUE THREAD

**Issue by barbastrejo12** [raspibolt/raspibolt#1300]
When is it safe to migrate to debian bookworm? Can we do it now, or better wait a few months?

**Comment by luksocculta** [comment]
It isn't safe. Pi OS is little different from main Debian so it isn't recommended to upgrade by Debian way. It's recommended to wait for official upgrade from Raspberry Pi site which probably be done in fee weeks. But it isn't prohibited. It can be successfull or not, you won't know unless you try. It strictly depends from configuration. I wanted to do some kind of Franken-Debian by only pointing repositories to Bookworm but this is also not recommended but many does systems like this and they say it works flawlessly. It's up to you. I give up after some struggles and will wait for official Raspi OS.

**Comment by barbastrejo12** [comment]
I see thanks for the info. Better wait then

**Comment by purpleKarrot** [comment]
A version of Raspberry Pi OS based on bookworm was released on 10.10.2023.
Release notes: https://downloads.raspberrypi.com/raspios_lite_arm64/release_notes.txt

**Comment by hellresistor** [comment]
I use this imges ..
https://raspi.debian.net/tested-images/
