### ISSUE TITLE
Electrs Error port 4224

### ISSUE THREAD

**Issue by moisesaer** [raspibolt/raspibolt#1301]
Hi, 
I am get error on my ELECTRS:

electrs --conf /data/electrs/electrs.conf
Starting electrs 0.9.14 on aarch64 linux with Config { network: Bitcoin, db_path: "/data/electrs/db/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.14 (Electrum Rust Server)!", signet_magic: f9beb4d9, args: [] }
Error: electrs failed

Caused by:
    failed to start HTTP server on 127.0.0.1:4224: Address already in use (os error 98)

I need help do solve this problem. Can anyone help me??

Thanks.

**Comment by romanz** [comment]
Seems to duplicate https://github.com/romanz/electrs/issues/894
