### ISSUE TITLE
Missing font/symbol

### ISSUE THREAD

**Issue by luksocculta** [raspibolt/raspibolt#1310]
### Describe the issue
Does anybody know why on overview here are missing some symbols?

### Location in guide
[Link to the corresponding page and section on <https://raspibolt.org>](https://raspibolt.org/guide/bonus/raspberry-pi/system-overview.html)

### Screenshots
![Screenshot_2023-07-08_00-04-24](https://github.com/raspibolt/raspibolt/assets/127668547/8c66dd22-718d-45c5-81f3-87ea6327c122)

### Environment
 - Hardware platform: [Raspberry Pi 4
 - Operating system: Raspberry Pi OS 64bit upgraded to bookworm
 - Version: Debian GNU/Linux 12 (bookworm)

### Additional context
There wasn't those symbols even before upgrading.

**Comment by luksocculta** [comment]
No, completely not related to bookworm. It was like that from beginning, I just didn't bother up to now because it's minor issue.

**Comment by Mynima** [comment]
> No, completely not related to bookworm. It was like that from beginning, I just didn't bother up to now because it's minor issue.

Hmm, super strange. I didn't have this issue at all on my side with a similar setup (only difference I saw was bookworm, hence the question).
