### ISSUE TITLE
[FEATURE REQ] Netdata

### ISSUE THREAD

**Issue by Deekee62** [raspibolt/raspibolt#1311]
### What

Add a guide that allows to install Netdata on Raspibolt.

### Why

Netdata gives far more insight than System overview in the Raspberry Pi Bonus Section

Netdata consists of a daemon that, when executed, is responsible for collecting and displaying information in real-time. It is a lightweight tool, mostly written in C, Python, and JavaScript, which uses minimal resources: about 2% on a single-CPU system.

Netdata is a free and open-source (FOSS) 

### How

A new bonus guide in the Raspberry Pi section, the installation is quite easy and can be installed using a single line installer and with only a few modification afterwards

### Animated GIF

![80827388-b9fee100-8b98-11ea-8f60-0d7824667cd3](https://github.com/raspibolt/raspibolt/assets/33904339/adab7756-9372-4466-a7c1-acfc8240fed4)

**Comment by Mynima** [comment]
Seems like a 'nice to have' tool, though we need to be careful with adding more projects onto a node. Remember that nodes with funds are hot wallets, users should choose carefully what software they install to minimize this risk where possible.

That said feel free to put together a PR and offer it up. People can choose their own risk profiles.

**Comment by Deekee62** [comment]
Unfortunately, I have never made a PR and might need some help!

**Comment by Deekee62** [comment]
well, to be honest I've not installed it yet on may RPi Umbrel node, but on an other RPI and the load seems to be minimal...
<img width="874" alt="image" src="https://github.com/raspibolt/raspibolt/assets/33904339/07d52385-13f3-4e26-a0af-427b350d5668">
<img width="871" alt="image" src="https://github.com/raspibolt/raspibolt/assets/33904339/7b6c60d9-5cc7-446a-aeea-930ee8902d4e">
