### ISSUE TITLE
[BUG] Shorten steps in Guide

### ISSUE THREAD

**Issue by Deekee62** [raspibolt/raspibolt#1316]
### Describe the bug
Shorten steps in Guide

### Location in guide
https://raspibolt.org/guide/bonus/lightning/lndg.html#blockchain-explorer
Why not in 1 step?
Replace:

- Open your LNDg website at https://raspibolt.local:8889 (replace raspibolt.local by your node’s IP address if necessary)

- Click on the “Advanced settings” link

With

- Open your LNDg website at https://raspibolt.local:8889/advanced (replace raspibolt.local by your node’s IP address if necessary)

### Expected behavior
N/A

### Screenshots
N/A

### Environment
N/A

### Additional context
N/A

**Comment by blckbx** [comment]
I think it's more intuitive the way it is described now.
