### ISSUE TITLE
How does the backup work?

### ISSUE THREAD

**Issue by ghost** [raspibolt/raspibolt#1334]
I would like to know more how the backup works? Does it generate a new static-channel-backup every time there's a new tx or routing event?

**Comment by twofaktor** [comment]
https://raspibolt.org/guide/lightning/channel-backup.html#why-are-lightning-channel-backups-important

**Comment by barbastrejo12** [comment]
> https://raspibolt.org/guide/lightning/channel-backup.html#why-are-lightning-channel-backups-important

is does not answer my questions: Does it generate a new static-channel-backup every time there's a new tx or routing event?

**Comment by twofaktor** [comment]
> > https://raspibolt.org/guide/lightning/channel-backup.html#why-are-lightning-channel-backups-important
> 
> is does not answer my questions: Does it generate a new static-channel-backup every time there's a new tx or routing event?

You need to read, it comes in the link that I have given you
