### ISSUE TITLE
Add lightning support to mempool block explorer [FEATURE REQ] 

### ISSUE THREAD

**Issue by raelschiffler** [raspibolt/raspibolt#1341]
### What & why

Is your feature request related to a problem, or a new addition to the guide? Provide a clear and concise description of what you'd like added to the RaspiBolt guide. If possible, please phrase it as a user story:

> As a user and enthusiast of this project, I want the mempool block explorer tutorial to contemplate lightning network features already present in the project, so that the Raspibolt project becomes even more features-full and complete.

### How

Describe the solution you're thinking of. Provide a clear and concise description of what you want to happen. Did you consider alternative options?

In the backend/mempool-config.sample.json file there's already a sample to do it!
Below is the content:
```
  "LIGHTNING": {
    "ENABLED": false,
    "BACKEND": "lnd",
    "STATS_REFRESH_INTERVAL": 600,
    "GRAPH_REFRESH_INTERVAL": 600,
    "LOGGER_UPDATE_INTERVAL": 30,
    "FORENSICS_INTERVAL": 43200,
    "FORENSICS_RATE_LIMIT": 20
  },
  "LND": {
    "TLS_CERT_PATH": "tls.cert",
    "MACAROON_PATH": "readonly.macaroon",
    "REST_API_URL": "https://localhost:8080",
    "TIMEOUT": 10000
  },
  "CLIGHTNING": {
    "SOCKET": "lightning-rpc"
  },
```
We only have to adapt it to the Raspibolt environment and add to the tutorial!

**Comment by raelschiffler** [comment]
Anyway there's a caveat in this request: I think it should contemplate the creation of another macarron file that does not embeds the same full authorizations the admin.macarron has. 
It's food for thought to check what access should it have and more details...
Related: https://github.com/lightningnetwork/lnd/issues/20

**Comment by raelschiffler** [comment]
I've found out the lightning explorer only works for paid mempool collaborators.

**Comment by twofaktor** [comment]
> I've found out the lightning explorer only works for paid mempool collaborators.

Where did you find this?
