### ISSUE TITLE
btcrpcexplorer - "No RPC connection"

### ISSUE THREAD

**Issue by kentschubert** [raspibolt/raspibolt#1342]
### Describe the issue
btc-rpc-explorer:   browser error message "No RPC connection"
- was working fine for months/year
- quite recently (not sure exactly when)

### Environment
 - raspberry pi 4; raspibolt v3 build
 - Raspberry Pi OS 64bit, Debian 11, ... ]
 - Debian GNU/Linux 11 (bullseye)
 - node -v
    v14.21.3
- npm -v
  6.14.18

### Additional context
checked .env and bitcoin.conf against documentation - nothing missing

**Comment by luksocculta** [comment]
Check if you entered all settings correctly. For example I uncommented but not corrected BTCEXP_BITCOIND_COOKIE in Configuration section. I left default and had exactly same error as you.
