### ISSUE TITLE
uvloop installing LNbits

### ISSUE THREAD

**Issue by Supersimmons** [raspibolt/raspibolt#1363]
### Describe the bug
Installing uvloop (0.16.0): Failed

### Location in guide
poetry install --only main

### Screenshots
• Installing uvloop (0.16.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-311
  creating build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/_version.py -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/_noop.py -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/__init__.py -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/_testbase.py -> build/lib.linux-x86_64-cpython-311/uvloop
  running egg_info
  writing uvloop.egg-info/PKG-INFO
  writing dependency_links to uvloop.egg-info/dependency_links.txt
  writing requirements to uvloop.egg-info/requires.txt
  writing top-level names to uvloop.egg-info/top_level.txt
  reading manifest file 'uvloop.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*' found under directory 'vendor/libuv/.git'
  warning: no previously-included files matching '*' found under directory 'vendor/libuv/docs'
  warning: no previously-included files matching '*' found under directory 'vendor/libuv/img'
  adding license file 'LICENSE-APACHE'
  adding license file 'LICENSE-MIT'
  writing manifest file 'uvloop.egg-info/SOURCES.txt'
  /tmp/tmpm_s_6om4/.venv/lib/python3.11/site-packages/setuptools/command/build_py.py:204: _Warning: Package 'uvloop.handles' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'uvloop.handles' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'uvloop.handles' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'uvloop.handles' to be distributed and are
          already explicitly excluding 'uvloop.handles' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  /tmp/tmpm_s_6om4/.venv/lib/python3.11/site-packages/setuptools/command/build_py.py:204: _Warning: Package 'uvloop.includes' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'uvloop.includes' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'uvloop.includes' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'uvloop.includes' to be distributed and are
          already explicitly excluding 'uvloop.includes' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  copying uvloop/cbhandles.pxd -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/cbhandles.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/dns.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/errors.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/loop.c -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/loop.pxd -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/loop.pyi -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/loop.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/lru.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/pseudosock.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/py.typed -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/request.pxd -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/request.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/server.pxd -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/server.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/sslproto.pxd -> build/lib.linux-x86_64-cpython-311/uvloop
  copying uvloop/sslproto.pyx -> build/lib.linux-x86_64-cpython-311/uvloop
  creating build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/async_.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/async_.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/basetransport.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/basetransport.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/check.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/check.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/handle.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/handle.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/idle.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/idle.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/pipe.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/pipe.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/poll.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/poll.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/process.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/process.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/stream.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/stream.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/streamserver.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/streamserver.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/tcp.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/tcp.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/timer.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/timer.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/udp.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  copying uvloop/handles/udp.pyx -> build/lib.linux-x86_64-cpython-311/uvloop/handles
  creating build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/__init__.py -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/compat.h -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/consts.pxi -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/debug.h -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/debug.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/flowcontrol.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/fork_handler.h -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/python.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/stdlib.pxi -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/system.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  copying uvloop/includes/uv.pxd -> build/lib.linux-x86_64-cpython-311/uvloop/includes
  running build_ext
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether make supports nested variables... yes
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking whether make supports the include directive... yes (GNU style)
  checking dependency style of gcc... gcc3
  checking for gcc way to treat warnings as errors... -Werror
  checking if gcc supports __attribute__(( visibility("default") ))... yes
  checking if gcc supports -fvisibility=hidden... yes
  checking if gcc supports -fno-strict-aliasing flag... yes
  checking if gcc supports -g flag... yes
  checking if gcc supports -std=gnu89 flag... yes
  checking if gcc supports -Wall flag... yes
  checking if gcc supports -Wextra flag... yes
  checking if gcc supports -Wno-long-long flag... yes
  checking if gcc supports -Wno-unused-parameter flag... yes
  checking if gcc supports -Wstrict-prototypes flag... yes
  checking for ar... ar
  checking the archiver (ar) interface... ar
  checking how to print strings... printf
  checking for a sed that does not truncate output... /usr/bin/sed
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for fgrep... /usr/bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /usr/bin/dd
  checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking whether make supports nested variables... (cached) yes
  checking whether gcc is Clang... no
  checking whether pthreads work with -pthread... yes
  checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
  checking whether more special flags are required for pthreads... no
  checking for PTHREAD_PRIO_INHERIT... yes
  checking for library containing dlopen... none required
  checking for library containing kstat_lookup... no
  checking for library containing gethostbyname... none required
  checking for library containing perfstat_cpu... no
  checking for library containing clock_gettime... none required
  checking for library containing sendfile... none required
  checking for library containing socket... none required
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking sys/ahafs_evProds.h usability... no
  checking sys/ahafs_evProds.h presence... no
  checking for sys/ahafs_evProds.h... no
  checking that generated files are newer than configure... done
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating libuv.pc
  config.status: executing depfiles commands
  config.status: executing libtool commands
    CC       src/libuv_la-fs-poll.lo
    CC       src/libuv_la-idna.lo
    CC       src/libuv_la-inet.lo
    CC       src/libuv_la-random.lo
    CC       src/libuv_la-strscpy.lo
    CC       src/libuv_la-threadpool.lo
    CC       src/libuv_la-timer.lo
    CC       src/libuv_la-uv-data-getter-setters.lo
    CC       src/libuv_la-uv-common.lo
    CC       src/libuv_la-version.lo
    CC       src/unix/libuv_la-async.lo
    CC       src/unix/libuv_la-core.lo
    CC       src/unix/libuv_la-dl.lo
  In file included from src/uv-common.h:42,
                   from src/uv-common.c:23:
  src/uv-common.c: In function ‘uv_walk’:
  src/queue.h:68:19: warning: storing the address of local variable ‘queue’ in ‘((void * (**)[2])MEM[(void *[2] * *)loop_13(D) + 16B])[1]’ [-Wdangling-pointer=]
     68 |     QUEUE_PREV(q) = (n);                                                      \
        |                   ^
  src/queue.h:78:7: note: in expansion of macro ‘QUEUE_SPLIT’
     78 |       QUEUE_SPLIT(h, q, n);                                                   \
        |       ^~~~~~~~~~~
  src/uv-common.c:491:3: note: in expansion of macro ‘QUEUE_MOVE’
    491 |   QUEUE_MOVE(&loop->handle_queue, &queue);
        |   ^~~~~~~~~~
  src/uv-common.c:487:9: note: ‘queue’ declared here
    487 |   QUEUE queue;
        |         ^~~~~
  src/queue.h:40:27: note: ‘((void * (**)[2])loop)[2]’ declared here
     40 |   ((const QUEUE *) (q) == (const QUEUE *) QUEUE_NEXT(q))
        |                           ^
  src/queue.h:74:9: note: in expansion of macro ‘QUEUE_EMPTY’
     74 |     if (QUEUE_EMPTY(h))                                                       \
        |         ^~~~~~~~~~~
  src/uv-common.c:491:3: note: in expansion of macro ‘QUEUE_MOVE’
    491 |   QUEUE_MOVE(&loop->handle_queue, &queue);
        |   ^~~~~~~~~~
    CC       src/unix/libuv_la-fs.lo
    CC       src/unix/libuv_la-getaddrinfo.lo
    CC       src/unix/libuv_la-getnameinfo.lo
    CC       src/unix/libuv_la-loop-watcher.lo
    CC       src/unix/libuv_la-loop.lo
    CC       src/unix/libuv_la-pipe.lo
    CC       src/unix/libuv_la-poll.lo
    CC       src/unix/libuv_la-process.lo
    CC       src/unix/libuv_la-random-devurandom.lo
    CC       src/unix/libuv_la-signal.lo
    CC       src/unix/libuv_la-stream.lo
    CC       src/unix/libuv_la-tcp.lo
    CC       src/unix/libuv_la-thread.lo
  In file included from ./src/uv-common.h:42,
                   from src/unix/internal.h:25,
                   from src/unix/stream.c:23:
  src/unix/stream.c: In function ‘uv__write_callbacks’:
  ./src/queue.h:68:19: warning: storing the address of local variable ‘pq’ in ‘((void * (**)[2])MEM[(void *[2] * *)stream_24(D) + 208B])[1]’ [-Wdangling-pointer=]
     68 |     QUEUE_PREV(q) = (n);                                                      \
        |                   ^
  ./src/queue.h:78:7: note: in expansion of macro ‘QUEUE_SPLIT’
     78 |       QUEUE_SPLIT(h, q, n);                                                   \
        |       ^~~~~~~~~~~
  src/unix/stream.c:944:3: note: in expansion of macro ‘QUEUE_MOVE’
    944 |   QUEUE_MOVE(&stream->write_completed_queue, &pq);
        |   ^~~~~~~~~~
  src/unix/stream.c:939:9: note: ‘pq’ declared here
    939 |   QUEUE pq;
        |         ^~
  ./src/queue.h:40:27: note: ‘((void * (**)[2])stream)[26]’ declared here
     40 |   ((const QUEUE *) (q) == (const QUEUE *) QUEUE_NEXT(q))
        |                           ^
  src/unix/stream.c:941:7: note: in expansion of macro ‘QUEUE_EMPTY’
    941 |   if (QUEUE_EMPTY(&stream->write_completed_queue))
        |       ^~~~~~~~~~~
  src/unix/thread.c: In function ‘uv__thread_stack_size’:
  src/unix/thread.c:195:24: warning: comparison of integer expressions of different signedness: ‘rlim_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
    195 |       if (lim.rlim_cur >= PTHREAD_STACK_MIN)
        |                        ^~
  src/unix/thread.c: In function ‘uv_thread_create_ex’:
  src/unix/thread.c:243:20: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
    243 |     if (stack_size < PTHREAD_STACK_MIN)
        |                    ^
    CC       src/unix/libuv_la-tty.lo
    CC       src/unix/libuv_la-udp.lo
    CC       src/unix/libuv_la-linux-core.lo
    CC       src/unix/libuv_la-linux-inotify.lo
    CC       src/unix/libuv_la-linux-syscalls.lo
  In file included from ./src/uv-common.h:42,
                   from src/unix/internal.h:25,
                   from src/unix/linux-inotify.c:23:
  src/unix/linux-inotify.c: In function ‘uv__inotify_fork’:
  ./src/queue.h:68:19: warning: storing the address of local variable ‘queue’ in ‘((void * (**)[2])MEM[(void *[2] * *)&tmp_watcher_list + 32B])[1]’ [-Wdangling-pointer=]
     68 |     QUEUE_PREV(q) = (n);                                                      \
        |                   ^
  ./src/queue.h:78:7: note: in expansion of macro ‘QUEUE_SPLIT’
     78 |       QUEUE_SPLIT(h, q, n);                                                   \
        |       ^~~~~~~~~~~
  src/unix/linux-inotify.c:133:5: note: in expansion of macro ‘QUEUE_MOVE’
    133 |     QUEUE_MOVE(&tmp_watcher_list.watchers, &queue);
        |     ^~~~~~~~~~
  src/unix/linux-inotify.c:92:9: note: ‘queue’ declared here
     92 |   QUEUE queue;
        |         ^~~~~
  ./src/queue.h:40:27: note: ‘*(void * (**)[2])((char *)&tmp_watcher_list + offsetof(struct watcher_list, watchers[0]))’ declared here
     40 |   ((const QUEUE *) (q) == (const QUEUE *) QUEUE_NEXT(q))
        |                           ^
  ./src/queue.h:74:9: note: in expansion of macro ‘QUEUE_EMPTY’
     74 |     if (QUEUE_EMPTY(h))                                                       \
        |         ^~~~~~~~~~~
  src/unix/linux-inotify.c:133:5: note: in expansion of macro ‘QUEUE_MOVE’
    133 |     QUEUE_MOVE(&tmp_watcher_list.watchers, &queue);
        |     ^~~~~~~~~~
    CC       src/unix/libuv_la-procfs-exepath.lo
    CC       src/unix/libuv_la-proctitle.lo
    CC       src/unix/libuv_la-random-getrandom.lo
    CC       src/unix/libuv_la-random-sysctl-linux.lo
    CC       src/unix/libuv_la-epoll.lo
    CCLD     libuv.la
  building 'uvloop.loop' extension
  creating build/temp.linux-x86_64-cpython-311
  creating build/temp.linux-x86_64-cpython-311/uvloop
  x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/tmpm_s_6om4/.venv/include -I/usr/include/python3.11 -I/tmp/tmpqtru7x02/uvloop-0.16.0/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-x86_64-cpython-311/uvloop/loop.o -O2
  uvloop/loop.c:214:12: fatal error: longintrepr.h: No such file or directory
    214 |   #include "longintrepr.h"
        |            ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with uvloop (0.16.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "uvloop (==0.16.0)"'.

### Environment
 - Hardware platform: Zimaboard
 - Operating system: Debian GNU/Linux 12 (bookworm)

**Comment by wankerstar** [comment]
What version of Python is installed? uvloop was broken for Python 3.12 on release and has seen been patched; not sure if that's the problem but the timing fits.

**Comment by hellresistor** [comment]
you need python3.9

maybe this solve your problem https://github.com/raspibolt/raspibolt/pull/1396
