### ISSUE TITLE
Unable to open cookie file '/home/bitcoin/.bitcoin/.cookie': Permission denied

### ISSUE THREAD

**Issue by hellresistor** [raspibolt/raspibolt#1375]
### Describe the bug
.cookie Permision denied, when run fulcrum
in bitcoin debug.log file returns 
"ThreadRPCServer incorrect password attempt from 127.0.0.1:45744
ThreadRPCServer incorrect password attempt from 127.0.0.1:42374"

### Location in guide
(https://raspibolt.org/guide/bonus/bitcoin/fulcrum.html#run-fulcrum)

### Screenshots
https://prnt.sc/v2ZfenJ9NxLD

### Environment
 - Raspberry Pi 4
 - Debian 12
 -  Debian GNU/Linux 12 (bookworm)

### Additional context
I have checked and rechecked :|

**Comment by mzdrowski** [comment]
Looks like the same issue is being discussed here: https://github.com/raspibolt/raspibolt/issues/1347

I reverted to rpcauth method to get Fulcrum working.

**Comment by hellresistor** [comment]
i am using rpcauth on bitcoin.conf :| can you share ?

**Comment by hellresistor** [comment]
well solved.

just this /data/fulcrum/fulcrum.conf

# Bitcoin Core settings
bitcoind = 127.0.0.1:8332
rpccookie = /data/bitcoin/.cookie
