### ISSUE TITLE
Upgrading to Debian Bookworm

### ISSUE THREAD

**Issue by purpleKarrot** [raspibolt/raspibolt#1382]
A version of Raspberry Pi OS based on bookworm was released on 10.10.2023.
Release notes: https://downloads.raspberrypi.com/raspios_lite_arm64/release_notes.txt

This is a duplicate of #1300. I did not find a way to reopen that issue.

**Comment by zynos** [comment]
This would also enable the PR https://github.com/raspibolt/raspibolt/pull/1327

**Comment by hellresistor** [comment]
use this ?
https://raspi.debian.net/tested-images/

**Comment by fdonnet** [comment]
question for people who used RaspiOS in the past, do you know if they will release a smooth dist-upgrade or we need to do it by ourself ?
