### ISSUE TITLE
OpenTimestamps client requires virtual environment to run

### ISSUE THREAD

**Issue by ShinyIsles** [raspibolt/raspibolt#1384]
Noob here. Hello all. 

Have got through the guide and have just completed IBD. 

Went to install the OpenTimestamps client as per instruction here – https://raspibolt.org/guide/bitcoin/bitcoin-client.html#opentimestamps-client

Python install seemed to go correctly with large output. Let me know if this is necessary for debug.

Installing OpenTimestamp-client results in the following:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Successfully installed it into a virtual environment. 

Is this the right way to go about this? Do I then donwload the updated core version and checksum files into the (env) and run them from there? Doesn't seem right but can't work out the way.

On a Raspi 4B with 8GB RAM and 2TB SSD, accessed via Terminal on iMac. Have updated to 25.1.

No LSB modules are available.
Description:	Debian GNU/Linux 12 (bookworm)

### Environment
 - Hardware platform: [e.g. Raspberry Pi 4, Odroid, ... ]
 - Operating system: [e.g, Raspberry Pi OS 64bit, Debian 11, ... ]
 - Version: [ output of `lsb_release -d` ]

**Comment by twofaktor** [comment]
Did you use Raspberry Pi OS (bullseye) debian 11 based? Or something different?

**Comment by twofaktor** [comment]
Raspibolt use debian 11 bullseye version, it has not been updated yet to the debian 12 bookworm version, you should use the bullseye version
