### ISSUE TITLE
Initial block download is incredibly slow

### ISSUE THREAD

**Issue by visskiss** [raspibolt/raspibolt#1390]
### Describe the issue
Even after updating to bitcoin core 26.0 I notice that the block download is incredibly slow. What I notice is that after restarting bitcoin core, the connections count goes to something "normal",  Using bitcoin-cli -netinfo I will see after ten minutes several outbound connections (around 10).

But when I check some hours later, there is a single connection. It has been two weeks of initial block download. Anyone have thoughts about this? Could it be Tor? Did something change with bitcoin core?  It has NEVER taken this long (usually around 5 days or a week)

### Environment
 - Hardware platform: pi 4 with recommended USB SSD (tested no issues with speed and using UASP)
 - Operating system: current as recommended in raspibolt
 -

**Comment by visskiss** [comment]
I was on that, which is why I upgraded to 26.0 hoping it would magically resolve.  Other node running 24.x is fine, but IBD was done long ago.

**Comment by kristapsk** [comment]
You could downgrade to 24.2 then and see is there any difference.

**Comment by hellresistor** [comment]
dons use tor to for sync ...
