### ISSUE TITLE
Debian GNU/Linux 12 (bookworm) Unable to install NGINX - directive "stream" (install libnginx-mod-stream not working)

### ISSUE THREAD

**Issue by tse64** [raspibolt/raspibolt#1432]
### Describe the issue
Installing NGINX, get the error : unknown directive "stream" -> did $ sudo apt install libnginx-mod-stream

result in the error:

///
dpkg: error processing package nginx (--configure):
 installed nginx package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of libnginx-mod-stream:
 libnginx-mod-stream depends on nginx-abi-1.22.1-7; however:
  Package nginx-abi-1.22.1-7 is not installed.
  Package nginx which provides nginx-abi-1.22.1-7 is not configured yet.

dpkg: error processing package libnginx-mod-stream (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nginx
 libnginx-mod-stream
E: Sub-process /usr/bin/dpkg returned an error code (1)
///

try to install nginx-abi-1.22.1-7  but  that is the result  

Note, selecting 'nginx' instead of 'nginx-abi-1.22.1-7'
nginx is already the newest version (1.22.1-9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.

### Location in guide
Install NGINX

### Screenshots

![Image 18-5-24 at 22 15](https://github.com/raspibolt/raspibolt/assets/170190523/cecd3492-bfc2-4bb2-a52f-215aa59f16b0)

### Environment
 PI5 - Bookworm

**Comment by lip2443** [comment]
This may solve:
sudo apt install libnginx-mod-stream
As explaines here:
https://raspibolt.org/guide/raspberry-pi/security.html#prepare-nginx-reverse-proxy
![image](https://github.com/raspibolt/raspibolt/assets/173169042/546aa0a7-179d-4ca0-b8ff-dd5032248c20)
