### ISSUE TITLE
disable ssh password login

### ISSUE THREAD

**Issue by Owl-lab425** [raspibolt/raspibolt#1441]
### Describe the bug
I followed the instruction on https://raspibolt.org/guide/raspberry-pi/security.html#disable-password-login but it wasn't possible to deactivate password login. I was still able to login without a key.

### Solution
I looked up google for other articles about how to disable ssh password login. I changed two more things but I don't know which one is the solution:
Either 1) uncomment "#ChallengeResponseAuthentication no" (in the manual you don't have to uncomment) or 2) use "sudo systemctl **reload** sshd" instead of "sudo systemctl **restart** sshd" (manual)
However, now it works. I get a "permission denied" for my computers without deposited keys. I guess the manual is missing one or both actions to finally disable password login.

Hope this can help fix this problem.

**Comment by kristapsk** [comment]
> Either 1) uncomment "#ChallengeResponseAuthentication no" (in the manual you don't have to uncomment) or 2) use "sudo systemctl **reload** sshd" instead of "sudo systemctl **restart** sshd" (manual)

Second definitely is not the issue, "restart" is harder action than "reload", always does what reload does too. "ChallengeResponseAuthentication no" change should be it. But it also looks that in recent OpenSSH versions it has changed to "KbdInteractiveAuthentication", see https://askubuntu.com/questions/1403846/ssh-challengeresponseauthentication-in-22-04-ubuntu .
