### ISSUE TITLE
LND Lightning Daemon keeps rescanning

### ISSUE THREAD

**Issue by acurious** [raspibolt/raspibolt#42]
Hi
I have run into an issue. My LND Lightning Daemon keeps rescanning from different blocks. It seems that it never finishes these tasks. Therefore, it seems it does not update the correct status of channels, either. Also, I can not close any channels nor make payments. Not sure, if it's related to this issue: https://github.com/lightningnetwork/lnd/issues/760
I have some funds in those channels. Any recommendations how to get these funds back?
![screenshot 2018-04-03 00 16 08](https://user-images.githubusercontent.com/35272855/38216943-21aee2d4-36d5-11e8-8c4b-caee2a48caf5.png)

**Comment by Stadicus** [comment]
Seems related, but I have not heard of this issue up until now. Is your bitcoind synced up with the Bitcoin network? Did you try to restart the whole node? How long did you let it run?

Might be a good idea to attach your input to the issue linked by you.

**Comment by acurious** [comment]
Yes, my bitcoind is synced with the Bitcoin network. I have restated the whole node several times. I let the node run for 6 hours without any progress

**Comment by acurious** [comment]
Update: seems like Raspberry Pi's processor can't handle load from LND. LND keeps rescanning, Pi's processor is constantly around 100%. Then LND hangs and processor usage by LND drops close to 0%.
