### ISSUE TITLE
FYI: LND V0.6 and Static Channel Backups

### ISSUE THREAD

**Issue by robclark56** [raspibolt/raspibolt#442]
Hi 

After upgrading to V0,6 (painless) added this to make sure I had offsite backups

https://github.com/robclark56/RaspiBolt-Extras/blob/master/RB_extra_backup_SCB.md

:-)

**Comment by giulnz** [comment]
In the same topic I tested this https://gist.github.com/vindard/e0cd3d41bb403a823f3b5002488e3f90
