### ISSUE TITLE
Trying to import an existing wallet and restore channels

### ISSUE THREAD

**Issue by ivoryz** [raspibolt/raspibolt#647]
I 'm trying to recover an existing wallet, i have the seed and channels.backup file.
I'm running a pi4, bitcoin is synced, I imported the wallet, i can see on-chain funds.
I executed the following cmd:
`lncli restorechanbackup --multi_file /tmp/channel.backup `

but nothing happen.What i'm missing?
Any help?

Thanks!

**Comment by lucasmoten** [comment]
For context, here is documentation on that capability of LND
https://github.com/lightningnetwork/lnd/blob/a998d5d64783d8b87e28fcc011ec8aa0e7adc444/docs/recovery.md#recovering-using-scbs

restorechanbackup is intended to recover funds and will close the channels.

It appears as though your command may be formed incorrectly.  Based on usage documentat linked above
```
USAGE:
   lncli restorechanbackup [command options] [--single_backup] [--multi_backup] [--multi_file=]
```

Consider changing your command to
```
lncli restorechanbackup --multi_file=/tmp/channel.backup
```
