### ISSUE TITLE
Create a mempool.space block explorer option to run as block explorer

### ISSUE THREAD

**Issue by raelschiffler** [raspibolt/raspibolt#651]
Sorry if this is outside the project/section scope, it's not even an issue, just a suggestion, but I like using mempool.space because it has a really cool design, features and layout and their project is also open source on github: https://github.com/mempool/mempool
You have a very didactic way to teach and it would be nice if you could add to the Block Explorer Section a guide to install mempool.space. Thanks a lot. I'm very thankful to you for teaching me how to create a full node on a Raspberry and it's all working fine. I've also tipped you.

**Comment by lucasmoten** [comment]
I'm looking into this following the guidance for the v1 version outlined here https://github.com/mempool/mempool#mempool-v1-not-using-docker-advanced. If I come up with anything I'll post it back here first.  If anyone else is working on adding mempool to raspibolt, please discuss here.

**Comment by Stadicus** [comment]
A bonus guide for mempool.space would be cool indeed :)

**Comment by raelschiffler** [comment]
Don't let it die.

**Comment by VajraOfIndra** [comment]
> Don't let it die.

Did you have a look at #870 ? We'd appreciate if you give the guide a try and send any feedback that could improve it!

**Comment by VajraOfIndra** [comment]
> Don't let it die.

@raelschiffler the Mempool bonus guide is [now published](https://raspibolt.org/bonus/bitcoin/mempool.html). For now it works within the LAN only, we need to add a remote connection via Tor. Feel free to propose ideas or PRs to improve the Mempool guide.

Can we close this Issue?

**Comment by raelschiffler** [comment]
> > Don't let it die.
> 
> @raelschiffler the Mempool bonus guide is [now published](https://raspibolt.org/bonus/bitcoin/mempool.html). For now it works within the LAN only, we need to add a remote connection via Tor. Feel free to propose ideas or PRs to improve the Mempool guide.
> 
> Can we close this Issue?

Yes, sure.

**Comment by raelschiffler** [comment]
> > Don't let it die.
> 
> @raelschiffler the Mempool bonus guide is [now published](https://raspibolt.org/bonus/bitcoin/mempool.html). For now it works within the LAN only, we need to add a remote connection via Tor. Feel free to propose ideas or PRs to improve the Mempool guide.
> 
> Can we close this Issue?

Hi, @VajraOfIndra. The link you provided is broken. Could you check please?

**Comment by VajraOfIndra** [comment]
> Hi, @VajraOfIndra. The link you provided is broken. Could you check please?

Yes, the link I provided was created before the big structural change we made in the repository. That change broke most external links to the guide unfortunately.

The Mempool bonus guide is now at: https://raspibolt.org/guide/bonus/bitcoin/mempool.html
