### ISSUE TITLE
Update Node JS to LTS = that is 14 right now

### ISSUE THREAD

**Issue by 2pac1** [raspibolt/raspibolt#685]
When installing btc explorer, there is old LTS Node JS version (12) in the guide:
Current: curl -sL https://deb.nodesource.com/setup_12.x | bash -

Proposed change: curl -sL https://deb.nodesource.com/setup_14.x | bash -

**Comment by LightningTwo** [comment]
I installed BTC RPC Explorer with NodeJS 14 and did not encounter any problems so far.
You could also change the command to `curl -sL https://deb.nodesource.com/setup_lts.x | bash -`
which always gets the latest LTS version.

**Comment by Stadicus** [comment]
I think the original topic of this issue has been taken care of with the recent update to RaspiBolt v3. I'm closing this issue, but feel free to reopen it if you think it's still unsolved.
