### ISSUE TITLE
bitcoind autostarter AFTER network is up

### ISSUE THREAD

**Issue by 2pac1** [raspibolt/raspibolt#686]
Current configs for autoboot: https://stadicus.github.io/RaspiBolt/raspibolt_30_bitcoin.html#autostart-on-boot

After=network.target

Maybe it would be better to change in accordance with
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

to: network-online.target

Would that be better suited for this purpose?

**Comment by Stadicus** [comment]
Good point, sorry to come back to this so late... :)

All services are very resilient against starting while the network is not yet ready. I'm not sure that this significantly improves node stability or performance, and would need some testing.

Do you think it's worth it?

**Comment by 2pac1** [comment]
Let's leave as it is

**Comment by Stadicus** [comment]
Ack, and thanks for the quick reply.
