### ISSUE TITLE
Link to Raspbian Buster Lite is broken

### ISSUE THREAD

**Issue by arminmayrhofer** [raspibolt/raspibolt#691]
The link contained in "Download the Raspbian Buster Lite disk image" on https://stadicus.github.io/RaspiBolt/raspibolt_20_pi.html#preparing-the-operating-system is broken.

**Comment by fatrattombala** [comment]
The Raspberry Pi Foundation now recommends installing Raspberry Pi OS (previously called Raspbian) via the Raspberry Pi Imager. Raspian Buster Lite is now called Rasperry Pi OS Lite (32 Bit), last version was released 2021-01-11.

![grafik](https://user-images.githubusercontent.com/67906279/105106694-a690fe80-5ab6-11eb-8c2a-050dc4c72c04.png)

**Comment by Stadicus** [comment]
I think the original topic of this issue has been taken care of with the recent update to RaspiBolt v3. I'm closing this issue, but feel free to reopen it if you think it's still unsolved.
