### ISSUE TITLE
Unable to remove *.macaroon when upgrading LND

### ISSUE THREAD

**Issue by viertelb** [raspibolt/raspibolt#734]
Not sure what is going on here:

```
admin@RPi4:/tmp $ sudo ls /home/bitcoin/.lnd/data/chain/bitcoin/mainnet -all
total 348
drwx--x--- 2 bitcoin bitcoin   4096 Dec  5  2020 .
drwx--x--- 3 bitcoin bitcoin   4096 Nov 25  2020 ..
-rw-r----- 1 bitcoin bitcoin    280 Nov 25  2020 admin.macaroon
-rw-r--r-- 1 bitcoin bitcoin     83 Nov 25  2020 chainnotifier.macaroon
-rw-r--r-- 1 bitcoin bitcoin     45 Dec  5  2020 channel.backup
-rw-r--r-- 1 bitcoin bitcoin    132 Nov 25  2020 invoice.macaroon
-rw-r--r-- 1 bitcoin bitcoin     91 Nov 25  2020 invoices.macaroon
-rw------- 1 bitcoin bitcoin  20480 Dec  5  2020 macaroons.db
-rw-r--r-- 1 bitcoin bitcoin    199 Nov 25  2020 readonly.macaroon
-rw-r--r-- 1 bitcoin bitcoin     91 Nov 25  2020 router.macaroon
-rw-r--r-- 1 bitcoin bitcoin     92 Nov 25  2020 signer.macaroon
-rw------- 1 bitcoin bitcoin 524288 Dec  7  2020 wallet.db
-rw-r--r-- 1 bitcoin bitcoin    114 Nov 25  2020 walletkit.macaroon
admin@RPi4:/tmp $ sudo rm /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/*.macaroon
rm: cannot remove '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/*.macaroon': No such file or directory

```

EDIT: Apart from this I suspect I don't have to delete anything since my previous LND version was >0.5 and I don't have to alter the config to upgrade. (https://stadicus.github.io/RaspiBolt/raspibolt_faq.html#how-to-upgrade-lnd) 

Maybe it is also interesting that I did not unlock the LND or use it. I just wanted to make sure it can be run.

EDIT: Also, installing LND seems to be different to what is used on the github install advice of the LND project. And veryfying the signatures does not look very good (although I know there had been issues when I first did this in 2020 already). (https://stadicus.github.io/RaspiBolt/raspibolt_40_lnd.html)

```
admin@RPi4:/tmp $ gpg --verify roasbeef-manifest-v0.11.1-beta.txt.sig manifest-v0.11.1-beta.txt
gpg: Signature made Fri 02 Oct 2020 02:03:47 CEST
gpg:                using RSA key 4AB7F8DA6FAEBB3B70B1F903BC13F65E2DC84465
gpg: Can't check signature: No public key

```

**Comment by bvrulez** [comment]
I was able to remove the `*.macaroon` files by their individual paths. After installing and restarting `lnd` I now get this error. When/How should the files be created again? 

```
admin@RPi4:/tmp $ lncli getinfo
[lncli] unable to read macaroon path (check the network setting!): open /home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory

```

**Comment by bvrulez** [comment]
I realized that my `lnd.conf` was missing two new entries. So I added them: 

```
protocol.achors=true
protocol.wumbo-channels=true
```

I thought maybe I deleted my wallet by deleting the `*.macaroon` files. Since I did not use `lnd` this would not have been a problem. But when I try to create a new wallet I get the error that a wallet already exists:

```
bitcoin@RPi4:~/.bitcoin $ lncli create
Input wallet password: 
Confirm password: 

Do you have an existing cipher seed mnemonic you want to use? (Enter y/n): n

Your cipher seed can optionally be encrypted.
Input your passphrase if you wish to encrypt it (or press enter to proceed without a cipher seed passphrase): 

Generating fresh cipher seed...

[lncli] unable to generate seed: rpc error: code = Unknown desc = wallet already exists

```

The original installation guide says "Check if the TLS certificates and admin.macaroon have been created." So I think, after deleting them they have to be created again. In which part of the process is this happening?

**Comment by bvrulez** [comment]
```
admin@RPi4:/mnt/bitcoin/lnd $ lnd --version
lnd version 0.11.1-beta commit=v0.11.1-beta

```

But 
```

admin@RPi4:/mnt/bitcoin/lnd $ lnd
/home/admin/.lnd/lnd.conf:10: unknown option: protocol.anchors

```

So, I guess the `protocol.anchors` option in the config is outdated?

**Comment by bvrulez** [comment]
Commenting this (`#protocoll.anchors=true`) works. Also, I deleted `~/.lnd/data` as per [here](https://github.com/lightningnetwork/lnd/issues/1216) to beeing prompted for a new wallet creating.

```
bitcoin@RPi4:~/.bitcoin $ lnd
Attempting automatic RPC configuration to bitcoind
Automatically obtained bitcoind's RPC credentials
2021-06-17 14:54:47.723 [INF] LTND: Version: 0.11.1-beta commit=v0.11.1-beta, build=production, logging=default
2021-06-17 14:54:47.723 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2021-06-17 14:54:47.769 [INF] LTND: Opening the main database, this might take a few minutes...
2021-06-17 14:54:47.769 [INF] LTND: Opening bbolt database, sync_freelist=false
2021-06-17 14:54:47.826 [INF] CHDB: Checking for schema update: latest_version=17, db_version=17
2021-06-17 14:54:47.826 [INF] LTND: Database now open (time_to_open=57.298256ms)!
2021-06-17 14:54:47.907 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2021-06-17 14:54:47.907 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2021-06-17 14:54:47.907 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

```

**Comment by bvrulez** [comment]
Using `lncli create` made a new wallet and created new macaroons. 

So, I guess the guide should be updated to reflect the fact that deleting `*.macaroons` means deleting your wallet? Not a problem for me since I do this just to stay up-to-date.

**Comment by Pantamis** [comment]
LND normally recreate macaroons file if there is none when you start it  

For anchors you must write
`protocol.anchors=1`

in configuration files (anchors are default starting from LND 0.12)

**Comment by Yasoj** [comment]
> admin@RPi4:/mnt/bitcoin/lnd $ lnd --version
> lnd version 0.11.1-beta commit=v0.11.1-beta
> [...]
> So, I guess the `protocol.anchors` option in the config is outdated?

On the contrary, the `protocol.anchors` setting was introduced in version 0.12-beta, so a more recent version that the one you installed. If/when you'll update your LND to the most recent version (0.13.0 as of now), you should then be able to use `protocol.anchors=1`, although I believe it is now the default).

**Comment by xanoni** [comment]
> On the contrary, the `protocol.anchors` setting was introduced in version 0.12-beta, so a more recent version that the one you installed. If/when you'll update your LND to the most recent version (0.13.0 as of now), you should then be able to use `protocol.anchors=1`, although I believe it is now the default).

`Version: 0.13.0-beta commit=v0.13.0-beta, build=production, logging=default, debuglevel=info`

`/home/lnd/.lnd/lnd.conf:10: unknown option: protocol.anchors`

tried `=1` and `=true`

sup?

**Comment by Pantamis** [comment]
> > On the contrary, the `protocol.anchors` setting was introduced in version 0.12-beta, so a more recent version that the one you installed. If/when you'll update your LND to the most recent version (0.13.0 as of now), you should then be able to use `protocol.anchors=1`, although I believe it is now the default).
> 
> `Version: 0.13.0-beta commit=v0.13.0-beta, build=production, logging=default, debuglevel=info`
> 
> `/home/lnd/.lnd/lnd.conf:10: unknown option: protocol.anchors`
> 
> tried `=1` and `=true`
> 
> sup?
> 
> (arch = armv7)

Anchor are activated by default in LND release 0.13.0. So the `protocol.anchors` settings is now `protocol.no-anchors` and it has the opposite behavior.

So if you installed LND 0.13.0 there is nothing to do to use anchor outputs !

**Comment by xanoni** [comment]
Thank you. Yes, I realized that. However, it's confusing that the example sample-lnd.conf still includes both settings.

**Comment by Stadicus** [comment]
I think this has been taken care of with the recent update to RaspiBolt v3. I'm closing this issue, but feel free to reopen it if you think it's still unsolved.
