### ISSUE TITLE
Improve System Recovery to facilitate upgrades

### ISSUE THREAD

**Issue by vicariousdrama** [raspibolt/raspibolt#755]
As referenced in issue #606, the [system recovery guidance](https://github.com/Stadicus/RaspiBolt/blob/master/raspibolt_65_system-recovery.md) should be enhanced to include cofiguration, wallet, channel backup files etc for LND.

This can then possibly be referenced to help faciliate migrations for new builds under 64 bit os vs 32 as recommended by #725

**Comment by Stadicus** [comment]
I'd like to add a bonus guide that writes all essential files (especially the SCB) to a permanently attached USB thumbdrive. I think that could then replace this outdated "system recovery guide", as a copy of the mSD card is no longer possible anyway.
