### ISSUE TITLE
Please at least REMOVE THIS GUIDE from public Internet

### ISSUE THREAD

**Issue by Kixunil** [raspibolt/raspibolt#769]
This guide is clearly unmaintained and if you don't want to spend time on it, it's OK but please remove it/replace with note saying you don't want to work on it anymore. This guide being published wastes time of people trying to use it and developers who need to respond to "doesn't work with RaspiBolt" bug reports.

**Comment by Kixunil** [comment]
Electrs guide is so outdated I'd call it pretty much broken. IDK about other software but I wouldn't dare to suggest people using it.

If @Stadicus found five minutes to remove it or at least add a warning about the current situation that'd be great minimal temporary fix.

**Comment by asvdf** [comment]
thank you for elaborating, been playing on a custom signet until now so I never really went past bitcoin+lnd yet, electrs was going to be the next step but I suppose I'll follow a generic guide

**Comment by Kixunil** [comment]
Note that even with LND you may want to use built-in auto unlock features that were implemented recently instead of external scripts (this has significant effect on reliability). It's not just that breaking changes are not updated but people don't get to use these important features. Anyway, good call trying with signet first.

**Comment by martinatime** [comment]
I think this is being solved by other means
https://twitter.com/Stadicus3000/status/1454065737543430144?s=20

**Comment by Kixunil** [comment]
Good, let's wait and see how it works out.

**Comment by kiteloopdesign** [comment]
Looks like the guide now located at https://raspibolt.github.io/raspibolt/ is exactly the same?
I still can see 32-Bits OS being recommended, and some other mistakes

**Comment by Kixunil** [comment]
Yeah, I would consider this resolved once there are a few contributors demonstrating that the guide is being updated.

**Comment by Stadicus** [comment]
@Kixunil, your tone is not appreciated. The guide is a bit out-of-date, but so is 99% of the rest on the internet. Plans are to fix the most important things first, and then work towards a version 3 that builds on a 64bit operation system.

If you don't like it, don't use it. Or contribute with a pull request.

I'm closing this issue.

**Comment by Kixunil** [comment]
@Stadicus thanks for helping move this forward, I definitely didn't want to offend you or anything like that. Everyone is busy from time to time and that's fine, I just asked you to clarify it for **other people**, as we got multiple issues at electrs directly related to this being out of date and it wasted both their time and our time. Sorry if my communication wasn't clear.

Given that you merged PRs etc I agree with this being closed. I will try to find some time checking electrs stuff and sending a PR.

**Comment by Stadicus** [comment]
Hey @Kixunil, no worries, thanks explaining. And sorry for being rude. Just yesterday I ran through the whole RaspiBolt setup (with Debian 64bit) and the Electrs part doesn't really need many changes as far as I can tell. 

The main issue is the Bitcoin Core authentication, but using a cookie and rpcauth in parallel works fine for Electrs (cookie or auth) and web services running as on a different service user.

If interested, you can check current progress on RaspiBlitz on Debian here (relevant for discussion here are the Bitcoin and Electrs sections):   
https://stadicus.github.io/raspibolt-remote/

**Comment by Kixunil** [comment]
Happy to hear it works! There's a bunch of potential improvements I explained in #747. Maybe I'll be able to do a PR today.
