### ISSUE TITLE
PROPOSAL (bonus section): decrease writing on SD Card with tmpfs

### ISSUE THREAD

**Issue by AsyncLuck** [raspibolt/raspibolt#790]
For the guys who have problem with their sd cards.

On my side, I loose the "sudo" lib because of a bad disk error (worst error ever).

I m trying to use tmpfs like this 
`sudo nano /etc/fstab`

Add this lines, to mount system folders that need writing directly in RAM 
You can tweak the size (the space used in ram)
```
tmpfs    /tmp    tmpfs    defaults,noatime,nosuid,size=100m    0 0

tmpfs    /var/tmp    tmpfs    defaults,noatime,nosuid,size=100m    0 0

tmpfs    /var/log    tmpfs    defaults,noatime,nosuid,mode=0755,size=100m    0 0

tmpfs    /var/run    tmpfs    defaults,noatime,nosuid,mode=0755,size=2m    0 0
```

If you use nginx, you can make a cron job to create its log folders/files because it doesn't create its structure by itself
`sudo crontab -e`

And add 
```
@reboot mkdir /var/log/nginx
@reboot touch /var/log/nginx/access.log
@reboot touch /var/log/nginx/error.log
```

`sudo reboot`

Maybe can be integrated in the backup/restore section.

++
EDIT : I will report if it's better after some times => 2 reflash in 1 week cause of errors on the sd card. I have big hopes because 2 times it was when I was trying to apt upgrade => maybe some big writing in /var/tmp. were bad for the SD.

EDIT2 : you will loose your logs at reboot. Maybe you can create a cron job to copy the files if it's really important for you on your /mnt/ext (SSD)

**Comment by Stadicus** [comment]
Thanks for this, very interesting. I'm currently working on the version 3 guide, however, that gets rid of the microSD card entirely. It's definitely great to have this information documented somewhere, but I'm not sure where it would still be relevant in the next version.

**Comment by AsyncLuck** [comment]
hi @Stadicus 
I think it is a great idea to get ride of the microSD => The weak point for a long term reliable pi node.
I will not have the motivation, for now, to migrate the system on the SSD and will try this ram method for some times. 

But for sure, it will be great, if you go with this approach (read only boot partition on the microSD + system on SSD or even no microSD at all) for the new happy followers of the raspibolt tuto ;)

**Comment by Stadicus** [comment]
Thanks for your contribution. I think this has been taken care of with the recent update to RaspiBolt v3. I'm closing this issue, but feel free to reopen it if you think it's still unsolved.

**Comment by AsyncLuck** [comment]
@Stadicus it is not working good... SD card failure again on strategic files. I m going with Raspibolt v3, without SD card, just now :)
