### ISSUE TITLE
failed to load config: ValidateConfig: either bitcoin.active or litecoin.active must be set to 1 (true)

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [raspibolt/raspibolt#792]
Not sure if it’s a but or a mal configuration from my side but if i’ll run lnd as bitcoin user first time i get following allert:
«failed to load config: ValidateConfig: either bitcoin.active or litecoin.active must be set to 1 (true)»

I did configuration as described in the new manual here: https://stadicus.github.io/raspibolt-remote/lnd.html
And as far as I understand bitcoin.active is set true:
<img width="695" alt="Screenshot 2021-11-24 at 11 42 13" src="https://user-images.githubusercontent.com/87816768/143223566-e4781bfb-4d8b-48de-a96c-ba4c9af5ddf5.png">

![screenshot1](https://user-images.githubusercontent.com/87816768/143222195-7b57ade9-e623-4fae-9060-021a8dda1810.jpg)

Any suggestions?

**Comment by Stadicus** [comment]
Is this still an unsolved issue? I ran through the RaspiBolt v3 setup several times from start to finish and never experienced this.

**Comment by xpsx** [comment]
I have the same problem, new setup

**Comment by n-e-t-d-i-v-e-r** [comment]
problem was that lnd-user isn’t operable with admin user anymore. running lnd must be executed with the lnd-user on raspibolt v3

**Comment by Stadicus** [comment]
Maybe you set up your v3 before this was merged? User "admin" should definitely be able to run `lncli`:

https://raspibolt.org/lnd.html#allow-user-admin-to-work-with-lnd
