### ISSUE TITLE
Any idea how to prevent electrum to connect autom

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [raspibolt/raspibolt#797]
Hi there

I try to connect my electrum wallet (macOS) with my private fullnode on raspibolt vs3. but allways if I try to connect electrum connects automatically, also if I uncheck the related box. As I can see there is another «rpc user and password filled in». As you can see on screenshot it is not my user which connect with electrum server:

<img width="644" alt="Screenshot 2021-11-27 at 15 15 47" src="https://user-images.githubusercontent.com/87816768/143685336-a55c519b-950d-4e68-85b5-eb1779e19828.png">

and server is up and running:
<img width="833" alt="Screenshot 2021-11-27 at 15 23 04" src="https://user-images.githubusercontent.com/87816768/143685444-e472adc4-df0a-4357-91fb-548e532529e7.png">

also newest version of tor-browser is installed and running on personal computer.

is there a chance to fill in «rpc user and PW» manually into the electrum.config?  I think I’m near on a running system, but it seems I can’t find the solution for my problem. With the new manual there is no chance to change rpc credentials manually anymore.

btw I can’t connect with localhost AND onion to my personal server ... In another issue I found a comment which means syncing has to be finished. Could this be the issue on my side to. How long this initial sync is going on?

<img width="1294" alt="Screenshot 2021-11-27 at 15 34 47" src="https://user-images.githubusercontent.com/87816768/143685897-91772487-bab1-47ef-971a-edfacffc8c68.png">

Thx for any support.

**Comment by Stadicus** [comment]
I'm not sure I understand what the problem is. 

Yes, Electrs must be fully synced, otherwise, you can't connect. You're right, that's not mentioned in the guide. Pull request https://github.com/raspibolt/raspibolt/pull/799 adds this remark

**Comment by n-e-t-d-i-v-e-r** [comment]
thx for response. yes, the «issue» was the missing info in the manual to sync electrum server fully before trying to connect wallet and server. I will close this.

**Comment by n-e-t-d-i-v-e-r** [comment]
thx for response. yes, the «issue» was the missing info in the manual to sync electrum server fully before trying to connect wallet and server. I will close this.
