### ISSUE TITLE
[FEATURE REQ] Add RaspiBolt v3.0 to the repo 'Releases' section

### ISSUE THREAD

**Issue by VajraOfIndra** [raspibolt/raspibolt#819]
### What & why

The 'Releases' section of the repo is still showing v2.1.  
Since v3 is now live we should probably update the section by adding this latest version.

### How

Create new release.

### Additional context

N/A

**Comment by Stadicus** [comment]
Yes, good point. I thought I'd give it some time in case there are still some bugs, but I think we're getting there :)

**Comment by Stadicus** [comment]
Added a PRE-RELEASE for now:

https://github.com/raspibolt/raspibolt/releases/tag/3.0-pre-release

**Comment by VajraOfIndra** [comment]
> I thought I'd give it some time in case there are still some bugs

I see, makes sense!

> Added a PRE-RELEASE for now:

Nice :)

**Comment by Stadicus** [comment]
Let's leave it open as a reminder to actually create the v3 soonish... :)

**Comment by Stadicus** [comment]
RaspiBolt v3 officially tagged! https://github.com/raspibolt/raspibolt/releases/tag/3.0
