### ISSUE TITLE
-bash: /usr/local/bin/lnd: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by jiyoon-koo** [raspibolt/raspibolt#843]
### Describe the issue
I have the bitcoin daemon running for a while, and I decided to install LND, following [this guide](https://raspibolt.org/lnd.html#download). Unfortunately I am running into an error and I'm not sure how it originates / why I'm getting this error. As far as I know, the raspberry pi is running raspbian which should be able to unpack and execute arm64 types.

### Location in guide
https://raspibolt.org/lnd.html#download in subsection `Install LND`

### Screenshots
Added
![image (3)](https://user-images.githubusercontent.com/12419157/146125339-497ea4e4-4256-42d3-a8a7-a8bf823dfeee.png)

### Environment
 - Raspberry Pi 4
 - Raspian GNU 11
 - 32 bit

Thank you for making this guide! It's been really fun so far.

**Comment by Stadicus** [comment]
Even if your Raspberry Pi 4 is 64-bit, you still seem to run Raspberry Pi OS 32-bit. Running 64-bit applications won't work unless you set up your Pi with a 64-bit operating system.

But most applications are available for 32 bit architectures, you just need to install the correct release binaries. For LND, this would be the following:

https://github.com/lightningnetwork/lnd/releases/download/v0.14.1-beta/lnd-linux-armv7-v0.14.1-beta.tar.gz

You can also check the (no longer maintained) version 2 of the RaspiBolt guide, which was using a 32-bit operating system:
https://v2.raspibolt.org/

**Comment by jiyoon-koo** [comment]
Ah, that makes a lot of sense! When I set up the node (about a month ago), I believe I was using the now "v2" version of raspibolt.org, and finished the Bitcoin section there.

Hopefully, the current guide will still be OK for me to follow along for the Lightning portion of it :) 

Thanks again!
