### ISSUE TITLE
Permissions issue bitcoind.service 

### ISSUE THREAD

**Issue by c-mannix** [raspibolt/raspibolt#853]
### Describe the issue
Followed the guide up to installing Bitcoin Core and my node is currently synching. However, when I check the status with `systemctl status bitcoind.service` I see `Warning: some journal files were not opened due to insufficient permissions.`  when running the command as `admin`.
 I get a different message when running the command as the `bitcoin` user, 
 `Warning: journal has been rotated since unit was started and some journal files were not opened due to insufficient permissions, output may be incomplete.`
 Do I need to change some permissions?

### Location in guide
https://raspibolt.org/bitcoin-core.html#running-bitcoind

### Screenshots
Screenshot with `admin` user:
<img width="1412" alt="Screen Shot 2021-12-24 at 8 12 37 AM" src="https://user-images.githubusercontent.com/96541162/147364006-ec72f1a3-5398-4f6d-aeef-c3fa053539db.png">
Screenshot with `bitcoin` user:
<img width="1411" alt="Screen Shot 2021-12-24 at 8 13 36 AM" src="https://user-images.githubusercontent.com/96541162/147364054-96089c74-f941-4b7d-b68f-fa5633da8e86.png">

Current permissions:

<img width="594" alt="Screen Shot 2021-12-24 at 8 30 14 AM" src="https://user-images.githubusercontent.com/96541162/147364705-444e3a9a-c106-4863-8da8-ee1a51c884b0.png">

### Environment
 - Hardware platform: Raspberry Pi 4
 - Operating system: Raspberry Pi OS 64bit
 - Version: Debian GNU/Linux 11 (bullseye)

**Comment by Stadicus** [comment]
I think that can be safely ignored for bitcoind, as we query the `debug.log` file directly, not using system logging.

If you run the "status" command you referenced with `sudo`, you should get the full output (but not much, or not more than in the log file)

**Comment by c-mannix** [comment]
It threw me off because the image shown in the guide did not have the warning that I was seeing so I thought I might have set some permissions incorrectly.

**Comment by Stadicus** [comment]
Good point. I just checked, and I get the same warning myself. The command listed in the guide is perfectly fine, we should just remove the following lines:

https://github.com/raspibolt/raspibolt/blob/3349f4d508b39121ca68303e75853efd49cecd8e/bitcoin-core.md?plain=1#L339-L342

**Comment by c-mannix** [comment]
May be a good idea to add the warning message as well. If someone doesn't see that they still may think they did something wrong because it differs from the actual output they see when running the command.
