### ISSUE TITLE
[FEATURE REQ] Update lntop bonus guide to v0.3.1

### ISSUE THREAD

**Issue by VajraOfIndra** [raspibolt/raspibolt#885]
### What & why

Just a note as a reminder for a contributor to update the lntop bonus guide to update it from v0.2.0 to v0.3.1: [https://github.com/edouardparis/lntop/releases](https://github.com/edouardparis/lntop/releases)

**Comment by marcosdub** [comment]
There aren't binaries avaliable for v0.3.1 arm64 arch yet. Better v0.3.0, avaliable binaries:
https://github.com/edouardparis/lntop/releases/tag/v0.3.0
https://github.com/edouardparis/lntop/releases/download/v0.3.0/lntop-v0.3.0-Linux-arm64.tar.gz

**Comment by VajraOfIndra** [comment]
> There aren't binaries avaliable for v0.3.1 arm64 arch yet. Better v0.3.0, avaliable binaries: https://github.com/edouardparis/lntop/releases/tag/v0.3.0 https://github.com/edouardparis/lntop/releases/download/v0.3.0/lntop-v0.3.0-Linux-arm64.tar.gz

Good point, updating to v0.3.0 instead sounds good.
