### ISSUE TITLE
[MOD REQ] Remove line "index_looup_limit" of electrs.conf

### ISSUE THREAD

**Issue by twofaktor** [raspibolt/raspibolt#888]
### What & why

Remove parameter "index_looup_limit" of electrs.conf, now limit is 200 txs by default.

In the last released of electrs: https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md#094-dec-30-2021 ... "Disable index_lookup_limit by default (635)" now, the number of transactions to lookup before returning an error, has risen to 200 txs in source code. (evindences below). Is not necessary.

### How

Remove parameter "index_lookup_limit" of electrs.conf:
```
# RaspiBolt: electrs configuration
# /data/electrs/electrs.conf

# Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/home/bitcoin/.bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"

# Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/data/electrs/db"

# Logging
log_filters = "INFO"
timestamp = true`
```
### Additional context

**Discussions:**

https://github.com/romanz/electrs/issues/635
https://github.com/romanz/electrs/pull/637

**Evidences & example devs conf:**

https://github.com/romanz/electrs/blob/cd348e72de9071549755170e9709ae922e023083/internal/config_specification.toml#L111-L115
https://github.com/romanz/electrs/blob/master/doc/config_example.toml

**Comment by Stadicus** [comment]
Sounds like a good change :+1:

**Comment by marcosdub** [comment]
Opening error
