### ISSUE TITLE
Mismatched Ports in Config

### ISSUE THREAD

**Issue by xmready** [raspibolt/raspibolt#892]
There is a mismatch between the port numbers in the bitcoin and electrs config files. I don't know if this is on purpose or a typo in the guide.

Bitcoin config shows ports 28332 & 28333 
`zmqpubrawblock=tcp://127.0.0.1:28332`
`zmqpubrawtx=tcp://127.0.0.1:28333`

electrs config sows ports 8332 & 8333
`daemon_rpc_addr = "127.0.0.1:8332"`
`daemon_p2p_addr = "127.0.0.1:8333"`

I'm guessing that rpc is for local connections and p2p is for other nodes? Thanks.

**Comment by Stadicus** [comment]
These are not the same services provide by these ports:

* `8332`: Bitcoin Core RPC API (to accept queries, e.g. from `bitcoin-cli`)
* `8333`: Bitcoin Core P2P network (to connect to other Bitcoin nodes)
* `28332`/`28333`: [ZeroMQ](https://zeromq.org/) ports used by LND to get notifications on new blocks and stuff

**Comment by xmready** [comment]
> These are not the same services provide by these ports:
> 
>     * `8332`: Bitcoin Core RPC API (to accept queries, e.g. from `bitcoin-cli`)
> 
>     * `8333`: Bitcoin Core P2P network (to connect to other Bitcoin nodes)
> 
>     * `28332`/`28333`: [ZeroMQ](https://zeromq.org/) ports used by LND to get notifications on new blocks and stuff

Thanks for the clarification. Maybe the guide could use a top level explanation, or some commented lines in the config.
