### ISSUE TITLE
[FEATURE REQ] Guide: Add "sudo" before commands

### ISSUE THREAD

**Issue by zynos** [raspibolt/raspibolt#908]
### What & why

> As a Guide reader, I want "sudo" added in front of those commands which require "sudo".

### How
In the guide at:
https://raspibolt.org/bitcoin-core.html#create-data-folder
The following commands will not work without "sudo" in front of them
```

$ mkdir /data/bitcoin
$ chown bitcoin:bitcoin /data/bitcoin

```
Can you change it to 

```

$ sudo mkdir /data/bitcoin
$ sudo chown bitcoin:bitcoin /data/bitcoin

```
?

Or did I do something wrong?

**Comment by RooSoft** [comment]
True... will create a pull request. Thanks!
