### ISSUE TITLE
[FEATURE REQ] Free NoIP SSL certificate signing

### ISSUE THREAD

**Issue by rafaelpac** [raspibolt/raspibolt#923]
### What & why

NoIP has a DDNS service with a free tier that is good enough for home users.

They are now offering a free SSL certificate
https://www.noip.com/blog/2021/12/17/ssl-certificate-now-included-with-free-dynamic-dns/

Could we get an update of the [NGINX Security](https://github.com/raspibolt/raspibolt/blob/master/security.md#prepare-nginx-reverse-proxy) section to use that?

**Comment by VajraOfIndra** [comment]
> ### What & why
> 
> NoIP has a DDNS service with a free tier that is good enough for home users.
> 
> They are now offering a free SSL certificate https://www.noip.com/blog/2021/12/17/ssl-certificate-now-included-with-free-dynamic-dns/

The link is dead for me.. is it just me?

> Could we get an update of the [NGINX Security](https://github.com/raspibolt/raspibolt/blob/master/security.md#prepare-nginx-reverse-proxy) section to use that?

Could you expand on how we would use this free SSL certificate in the context of the RaspiBolt? what benefits we'd get? (genuine question as I'm still very unfamiliar with how SSL, nginx and all this work! although maybe it's not the place for such beginner's question; if so, feel free to ignore it! :)

**Comment by rafaelpac** [comment]
I believe that NoIP as a whole is down now (it is kind of intermittent).
The use case I was thinking about is that I might, for example, want to share my block explorer with a friend/family and I don't want it to show the default browser warning of a self-signed certificate.
Also, some app might not accept self signed certificates to connect to the Electrum server (python requests, for example, will not accept self signed certificates by default: https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate).
So, this free SSL certificate could help with that while still keeping everything free, you don't need to pay for a domain or certificate (you can get a free signed certificate if you have a domain, with letsencrypt or zerossl, but this is the only way I know to have a free DDNS domain with a free certificate).

**Comment by RooSoft** [comment]
As far as sharing apps such as block explorers, here's an idea to avoid doing port forwarding or even exposing any of my local IPs... It's somewhat more complicated, but it seems safer to me.

* Rent a cheap VPS 
* Install wireguard on it
* Install wireguard on Raspibolt
* Make sure the raspibolt connect to the VPS's wireguard on startup
* Make sure it reconnects upon dynamic IP change
* Expose services locally on HTTP
* Install a reverse proxy on the VPS with let's encrypt
* Attach a DNS entry to the VPS

With such a setup, any app can be exposed to the public with TLS, a domain name and minimal local network security impact.

WDYAT?

**Comment by visskiss** [comment]
Raspibolt is designed to work on a local network. As such, you can't use signed certificates unless you expose the Pi to the external network and attach a domain name to it. If you do that, I recommend letsencrypt. It has bots that automagically manage the signing for you. In any case, the MUCH BETTER WAY OF DOING THIS is to expose the onion hidden service and instruct anyone who wants access to install TOR and use that address.
