### ISSUE TITLE
[FEATURE REQ] Guide: Add note in Open channel section

### ISSUE THREAD

**Issue by zynos** [raspibolt/raspibolt#925]
### What ?
In the section
https://raspibolt.org/lnd.html#opening-channels
under the heading 
`Open a channel using the <pubkey> and the channel capacity in satoshis.`
Could you add a Note saying:
`Attention! : Remove the part of the adress starting with the first "@" sign`
?

### Why ?
I accidently reused the full URI including the Port and got this error message:
`Cannot open channel: [lncli] unable to decode node public key: encoding/hex: invalid byte: U+0040 '@' `
see more on this: https://github.com/lightningnetwork/lnd/issues/6264

I think it is really helpful nor beginners to pay attention to the different format of URL / pubkey and a little note could help avoiding problems like mine

**Comment by VajraOfIndra** [comment]
> I think it is really helpful nor beginners to pay attention to the different format of URL / pubkey and a little note could help avoiding problems like mine

Although the difference between the URI and pubkey is explained at the start of the section, it is true that it can be easily missed for a new user when reaching the openchannel command...

I wrote #926 to implement your suggestions. PTAL and give feedback there if you like it or not.
