### ISSUE TITLE
Node will not connect to blockchain explorer

### ISSUE THREAD

**Issue by uskrusader** [raspibolt/raspibolt#949]
I ran through this part of the guide twice, verified the .env file, hopefully it is in the right place.  
but it still wont connect to BTC explorer for some reason.  
The last pic at bottom would indicate node is operating fine though, right? 

### Location in guide
https://raspibolt.org/guide/bitcoin/blockchain-explorer.html
![guidebtcrpcexplorer](https://user-images.githubusercontent.com/77032141/156836427-583997b6-3dfe-494e-bdba-c9eb56e3d5c5.png)

![4mar22npmrun](https://user-images.githubusercontent.com/77032141/156836905-c262d99a-cc15-49cf-8bab-35d50aba9f09.png)

regular connection
![4mar22noconnect](https://user-images.githubusercontent.com/77032141/156836724-1e977f8d-3d25-4350-a16d-867cf126cb8b.png)

through TOR
![4mar22tornoconnect](https://user-images.githubusercontent.com/77032141/156836795-4dfc960e-d12a-44bb-96fd-f0fd4a804d1c.png)

The node is working fine right?  If electrum wallet works with one blue button tor connection with .onion addy I got by following this guide.  I did the small transaction with it only connected to the one nod.

![4mar22nodeworks](https://user-images.githubusercontent.com/77032141/156837659-30d59bb4-a7a4-4a63-b7e1-9df144f94d01.png)

### Environment
 Raspberry Pi 4, 
 - Operating system: [e.g, Raspberry Pi OS 64bit, Debian 11, ... ]

**Comment by Stadicus** [comment]
> The node is working fine right? If electrum wallet works with one blue button tor connection with .onion addy I got by following this guide. I did the small transaction with it only connected to the one nod.

That's working as expected, nothing to do here :)

**Comment by Stadicus** [comment]
Your BTC RPC Explorer configuration file is also loaded correctly, looks good. But there's an error message about the port already being in use. Maybe the Explorer is already running in the background. I'd recommend a restart of the RaspiBolt and checking the log immediately after boot:

```sh
sudo journalctl -u btcrpcexplorer -f
```

You can also check the Bitcoin Core log if there are any error messages resulting from the Explorer trying to fetch data with wrong credentials:

```
tail -f /data/bitcoin/debug.log
```

**Comment by Stadicus** [comment]
Another common issue is that the Explorer does not reload the `.cookie` information if it changes, for example, because Bitcoin Core is restarted, but the Explorer was already running.

See here: https://github.com/janoside/btc-rpc-explorer/issues/393

In that case, try restarting the Explorer systemd unit (the background service) with

```
sudo systemctl restart btcrpcexplorer
```

**Comment by uskrusader** [comment]
> Another common issue is that the Explorer does not reload the `.cookie` information if it changes, for example, because Bitcoin Core is restarted, but the Explorer was already running.
> 
> See here: [janoside/btc-rpc-explorer#393](https://github.com/janoside/btc-rpc-explorer/issues/393)
> 
> In that case, try restarting the Explorer systemd unit (the background service) with
> 
> ```
> sudo systemctl restart btcrpcexplorer
> ```

that fixed it !!!
thank you much!
