### ISSUE TITLE
[BUG]  Incorrect command in mempool space install

### ISSUE THREAD

**Issue by visskiss** [raspibolt/raspibolt#966]
### Describe the bug
Chown command is executed, but it should be chmod

sudo chown 600 /home/mempool/mempool/backend/mempool-config.json

should be 

sudo chmod 600 /home/mempool/mempool/backend/mempool-config.json

### Location in guide

[https://raspibolt.org/guide/bonus/bitcoin/mempool.html](https://raspibolt.org/guide/bonus/bitcoin/mempool.html)

**Comment by VajraOfIndra** [comment]
Thanks @visskiss! Would you be interested to write a PR for the the issues you've idenitifed?

There are also issues #918 and #919 that concerns the Mempool guide. We could maybe do one PR that fixes the four issues at once maybe.. wdyt?

**Comment by visskiss** [comment]
Yes, happy to assist. Do you want me to branch off master and then organize a pull request or do you have some other system (git flow?).

**Comment by VajraOfIndra** [comment]
> Yes, happy to assist.

Thanks a lot! :)

> Do you want me to branch off master and then organize a pull request or do you have some other system (git flow?).

I don't think we'be been using git flow so far.. but I'll let @Stadicus answer you on this though as I'm very inexperienced with git.
