### ISSUE TITLE
Should Mempool be promoted to the main guide?

### ISSUE THREAD

**Issue by RooSoft** [raspibolt/raspibolt#969]
<img width="362" alt="Screen Shot 2022-03-15 at 3 50 20 PM" src="https://user-images.githubusercontent.com/665949/158459895-dd0160f7-3e57-484f-8dd9-485f220e7ffa.png">

Just to make a followup on that poll... Should Mempool be promoted to the main guide?

**Comment by VajraOfIndra** [comment]
Thanks @RooSoft for an interesting proposal.

Based on mentions in social media posts, it does seem that Mempool is a more popular than the BTC RPC Explorer as an explorer and mempool visualizer... and your poll seem to confirm this, although the gap is fairly small.

While this popularity justifies a possible switch from the Explorer to Mempool in the core guide, I am a bit concerned about its resource footprint as it uses significantly more CPU (and RAM?) than the Explorer. It can still be easily run on a Pi 4 though so not sure if it should be held against it, but just wanted to point out this aspect for discussions.

Mempool is also a bit harder to install as it requires to configure a nginx web server.. but again, probably not so complicated as to prevent being part of the core guide.

I never dwelve too much in the functionalities of both the Explorer and Mempool other than the main functions so not sure how they compare on that point..?

So to conclude, IMHO, I don't feel an urgent need to switch to replace the Explorer with Mempool, but I'm not against doing it either! (unless a serious issue is pointed out by someone).
