### ISSUE TITLE
[BUG] Wrong path for the target of "df" in the SCB backup guide

### ISSUE THREAD

**Issue by VajraOfIndra** [raspibolt/raspibolt#981]
### Describe the bug
Bug reported here by Telegram user @El_Stone: [https://t.me/raspibolt/9325](https://t.me/raspibolt/9325)

In the SCB backup guide, the command `df -h static-channel-backup-external` returns an error message `df: static-channel-backup-external: No such file or directory`.

### Location in guide
At the end of the following section: https://raspibolt.org/guide/lightning/channel-backup.html#formatting

### Expected behavior
The command should output the expected information.

### Proposed fix
Use the absolute path of the folder: `df -h /mnt/static-channel-backup-external`

**Comment by mktech-gh** [comment]
My Pull Request #983 fix this Issue.
